{
 "title": "Current session with CPU / Memory usage",
 "time": { "from": "2026-02-23T22:42:35.468Z", "to": "2026-02-24T10:42:35.468Z" },
 "templating": {
  "list": [
   { "name": "Server", "label": "Server / Instance", "query": "PLER0101\\PRNP" }
  ]
 },
 "panels": [
  {
   "title": "Current session with CPU / Memory usage",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "${Server}",
     "rawSql": "SELECT\r\n    r.session_id,\r\n    s.login_name,\r\n    s.host_name,\r\n    r.status,\r\n    r.cpu_time,\r\n    r.total_elapsed_time,\r\n    r.wait_type,\r\n    r.wait_time,\r\n    r.granted_query_memory * 8 AS granted_memory_kb,\r\n    r.logical_reads,\r\n    r.reads,\r\n    r.writes,\r\n    DB_NAME(r.database_id) database_name,\r\n    t.text query_text\r\nFROM sys.dm_exec_requests r\r\nJOIN sys.dm_exec_sessions s\r\n    ON r.session_id = s.session_id\r\nCROSS APPLY sys.dm_exec_sql_text(r.sql_handle) t\r\nWHERE s.is_user_process = 1\r\nORDER BY r.cpu_time DESC;"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "FLEXNET",
     "rawSql": "set nocount on\r\nCREATE TABLE #sp_who2 (SPID INT,Status VARCHAR(255),\r\n      Login  VARCHAR(255),HostName  VARCHAR(255),\r\n      BlkBy  VARCHAR(255),DBName  VARCHAR(255),\r\n      Command VARCHAR(255),CPUTime INT,\r\n      DiskIO INT,LastBatch VARCHAR(255),\r\n      ProgramName VARCHAR(255),SPID2 INT,\r\n      REQUESTID INT)\r\nINSERT INTO #sp_who2 EXEC sp_who2\r\n\r\nSELECT\r\nCPU  Value\r\nFROM \r\n(Select Avg([SQLProcessUtilization]) CPU ,count(record_id) Prc From\r\n(  ​​​​ SELECT​​ record.value('(./Record/@id)[1]',​​ 'int')​​ AS​​ record_id,​​ \r\n   record.value('(./Record/SchedulerMonitorEvent/SystemHealth/ProcessUtilization)[1]',​​ 'int')​​ \r\n   AS​​ [SQLProcessUtilization]\r\n  ​​​​ FROM​​ (​​ \r\n   SELECT​​ [timestamp],​​ CONVERT(xml,​​ record)​​ AS​​ [record]​​ \r\n   FROM​​ sys.dm_os_ring_buffers​​ WITH​​ (NOLOCK)\r\n   WHERE​​ ring_buffer_type​​ =​​ N'RING_BUFFER_SCHEDULER_MONITOR'​​ \r\n   AND​​ record​​ LIKE​​ N'%<SystemHealth>%')​​ AS​​ x​​ ) c) n ,\r\n(SELECT      count(*) Cnt FROM  #sp_who2) m\r\n \r\nDROP TABLE #sp_who2"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "FLEXNET",
     "rawSql": "\tselect cast(100 *\r\n(SELECT 100* CAST(physical_memory_in_use_kb/1024 AS DECIMAL(18,2))\r\nFROM sys.dm_os_process_memory)\r\n/\r\n(SELECT 100 * CAST(total_physical_memory_kb/1024 AS DECIMAL(18,2))\r\nFROM sys.dm_os_sys_memory)\r\nas decimal(18,2)) As 'Percentage_Used'"
    }
   ]
  }
 ]
}