{
 "title": "ITE MOM",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "templating": {
  "list": [
   {
    "name": "Group",
    "query": "SELECT GroupName FROM ESSTH.dbo.Groups WHERE Enable = 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Change Order Closed",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT chg_ref_num AS ChangeOrderNumber, summary AS Summary, open_date AS OpenDate, close_date AS CloseDate, status AS Status, priority AS Priority, assignee AS Assignee\r\n\tFROM [ESSTH].[dbo].[ChangeOrders]\r\n\tWHERE 1 = 1\r\n\t  AND $__timeFilter(open_date)\r\n\t\tAND [group] IN ($Group)\r\n\t\tAND status = 'Closed'\r\n\t\tAND open_date IS NOT NULL"
    }
   ]
  },
  {
   "title": "Change Order In Progress",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT chg_ref_num AS ChangeOrderNumber, summary AS Summary, open_date AS OpenDate, status AS Status, priority AS Priority, assignee AS Assignee\r\n\tFROM [ESSTH].[dbo].[ChangeOrders]\r\n\tWHERE 1 = 1\r\n\t\tAND [group] IN ($Group)\r\n\t\tAND status NOT IN ('Closed','Cancelled')\r\n\t\tAND open_date IS NOT NULL"
    }
   ]
  },
  {
   "title": "Change Order Backlog",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(DATEADD(MONTH, DATEDIFF(MONTH, 0, OpenDate), 0), (DATEADD(MONTH, DATEDIFF(MONTH, 0, CloseDate), 0))) AS time\r\n\t,OpenCount\r\n\t,CloseCount\r\n\t,SUM(OpenCount) OVER (\r\n\t\tORDER BY OpenDate ROWS BETWEEN UNBOUNDED PRECEDING\r\n\t\t\t\tAND CURRENT ROW\r\n\t\t) - SUM(CloseCount) OVER (\r\n\t\tORDER BY CloseDate ROWS BETWEEN UNBOUNDED PRECEDING\r\n\t\t\t\tAND CURRENT ROW ) AS BackLog\r\nFROM (\r\n\tSELECT DATEADD(MONTH, DATEDIFF(MONTH, 0, open_date), 0) AS OpenDate\r\n\t\t,COUNT(*) AS OpenCount\r\n\tFROM [ESSTH].[dbo].[ChangeOrders]\r\n\tWHERE 1 = 1\r\n\t\tAND [group] IN ($Group)\r\n\t\tAND status <> 'Cancelled'\r\n\tGROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, open_date), 0)\r\n\t) O\r\nFULL OUTER JOIN (\r\n\tSELECT DATEADD(MONTH, DATEDIFF(MONTH, 0, close_date), 0) AS CloseDate\r\n\t\t,COUNT(*) AS CloseCount\r\n\tFROM [ESSTH].[dbo].[ChangeOrders]\r\n\tWHERE 1 = 1\r\n\t\tAND [group] IN ($Group)\r\n\t\tAND status <> 'Cancelled'\r\n\tGROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, close_date), 0)\r\n\t) C ON O.OpenDate = C.CloseDate\r\nWHERE COALESCE(OpenDate, CloseDate) IS NOT NULL\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Change Order Backlog",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "EXEC [dbo].[USP_WOM_ChangeOrderSummary] @Group = $Group, @Date = $__timeFrom()"
    }
   ]
  }
 ]
}