{
 "title": "MSSQL Overview MOMA BackupCopy",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(mssql_dba_database_totaldbsize_size_bytes,host)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mssql_dba_database_totaldbsize_size_bytes,db)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(mssql_dba_database_totaldbsize_size_bytes,type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Metric(s) Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Metric ( Last Updated)",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time({__name__=~\"mssql_dba_.*\"}[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Instance(s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (host) (\r\n  count by (host) (last_over_time(mssql_dba_database_useddbsize_size_bytes[1d]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Database(s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (host_name) (mssql_dba_database_totaldbsize_size_bytes)",
     "legendFormat": "{{host}} // {{db}} // {{type}}"
    }
   ]
  },
  {
   "title": "Total DBSize",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mssql_dba_database_totaldbsize_size_bytes{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocking / DeadLock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Blockings",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "mssql_dba_custom_blocking_count{instance_name=~\"$hostname\"}",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "Database Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "mssql_dba_deadlocks_count{instance_name=~\"$hostname\"}",
       "legendFormat": "{{instance_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Disk Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "mssql_dba_disk_usage_percentage_maximum_Percent{host_name=~\"$hostname\"}",
       "legendFormat": "{{host_name}} // {{Drive_name}}"
      }
     ]
    },
    {
     "title": "Database Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mssql_dba_database_totaldbsize_size_bytes{host=~\"$hostname\", db=~\"$instance\", type=~\"$type\"}",
       "legendFormat": "{{host}} // {{db}} // {{type}}"
      }
     ]
    },
    {
     "title": "Database Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "mssql_dba_db_status_ratio{instance_name=~\"$hostname\",database_name=~\"$instance\"}",
       "legendFormat": "{{instance_name}} // {{ database_name}}"
      }
     ]
    },
    {
     "title": "DB Free Size",
     "type": "volkovlabs-table-panel",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum by (host, db, type) (\r\n  last_over_time(mssql_dba_database_maxdbsize_size_bytes[30m])\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (host, db, type) (\r\n  last_over_time(mssql_dba_database_useddbsize_size_bytes[30m])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Shipping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "LogShipping Latency",
     "type": "volkovlabs-table-panel",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "last_over_time(mssql_dba_logshipping_restore_latency[7d])",
       "legendFormat": "{{host_name}} // {{ sqlserver_database_name}}"
      },
      {
       "expr": "last_over_time(mssql_dba_logshipping_backup_latency[7d])",
       "legendFormat": "__auto"
      },
      {
       "expr": "last_over_time(mssql_dba_logshipping_copy_latency[7d])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Latency",
     "type": "volkovlabs-table-panel",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "last_over_time(mssql_dba_replication_latency[30m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "mssql_dba_replication_latency[30d]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Backup",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "mssql_dba_db_backup_date{host_name=~\"$hostname\",sqlserver_database_name=~\"$instance\"}",
       "legendFormat": "{{host_name}} // {{ sqlserver_database_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "volkovlabs-table-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "last_over_time(mssql_dba_cpu_percent_maximum_Percent[30m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "last_over_time(mssql_dba_cpu_percent_maximum_Percent[30d])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "volkovlabs-table-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "last_over_time(mssql_dba_memory_maximum_Percent[30m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "last_over_time(mssql_dba_memory_maximum_Percent[30d])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Alawys On Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "AAG Status",
     "type": "volkovlabs-table-panel",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "mssql_dba_custom_alwayson_healthy_ratio[12h]",
       "legendFormat": "__auto"
      },
      {
       "expr": "mssql_dba_custom_alwayson_healthy_ratio[30d]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Agent Job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Agent Job ",
     "type": "volkovlabs-table-panel",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(mssql_dba_custom_agent_Job_result[30m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "last_over_time(mssql_dba_custom_agent_Job_result[30d])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}