{
 "title": "MSSQL Overview MOMA",
 "tags": [ "MSSQL" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(mssql_dba_database_totaldbsize_size_bytes,host_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mssql_dba_database_totaldbsize_size_bytes,db)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(mssql_dba_database_totaldbsize_size_bytes,type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Metric(s) Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "group by (host_instance) (\r\n  label_join(\r\n    last_over_time(mssql_dba_custom_blocking_count[1d]),\r\n    \"host_instance\",\r\n    \"\\\\\",\r\n    \"host_name\",\r\n    \"instance_name\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric ( Last Updated)",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time({__name__=~\"mssql_dba_.*\"}[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Instance(s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (host_name) (\r\n  count by (host_name,instance_name) (last_over_time(mssql_dba_custom_blocking_count[1d]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Database(s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (host_name) (mssql_dba_database_useddbsize_size_bytes)/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total DBSize",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mssql_dba_database_useddbsize_size_bytes[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Blocking / DeadLock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Database Blockings",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "mssql_dba_custom_blocking_count",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Database Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "mssql_dba_deadlocks_count", "legendFormat": "{{instance_name}}" }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Database Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mssql_dba_disk_usage_percentage_maximum_Percent",
     "legendFormat": "{{host_name}} // {{Drive_name}}"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mssql_dba_database_totaldbsize_size_bytes{host_name=~\"$hostname\", db=~\"$instance\", type=~\"$type\"}",
     "legendFormat": "{{host}} // {{db}} // {{type}}"
    }
   ]
  },
  {
   "title": "Database Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "mssql_dba_db_status_ratio",
     "legendFormat": "{{instance_name}} // {{ database_name}}"
    }
   ]
  },
  {
   "title": "DB Free Size",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (host_name,instance, db, type) (\r\n  last_over_time(mssql_dba_database_maxdbsize_size_bytes[30m])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_name,instance, db, type) (\r\n  last_over_time(mssql_dba_database_useddbsize_size_bytes[30m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Log Shipping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "LogShipping Latency",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "last_over_time(mssql_dba_logshipping_restore_latency[70d])",
     "legendFormat": "{{host_name}} // {{ sqlserver_database_name}}"
    },
    {
     "expr": "last_over_time(mssql_dba_logshipping_backup_latency[70d])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(mssql_dba_logshipping_copy_latency[70d])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Replication Latency",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "last_over_time(mssql_dba_replication_latency[30m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "mssql_dba_replication_latency[30d]",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Database Backup",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "max by (\r\n  BackupType,\r\n  RecoveryModel,\r\n  host_name,\r\n  sqlserver_database_name\r\n)(\r\n  mssql_dba_db_backup_date\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(\r\n  (time() -\r\n   max by (\r\n     BackupType,\r\n     RecoveryModel,\r\n     host_name,\r\n     sqlserver_database_name\r\n   )(mssql_dba_db_backup_date)\r\n  ) / 86400\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "CPU Usage",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "last_over_time(mssql_dba_cpu_percent_maximum_Percent[30m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(mssql_dba_cpu_percent_maximum_Percent[30d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "last_over_time(mssql_dba_memory_sqlserver_percent[30m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(mssql_dba_memory_sqlserver_percent[30d])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alawys On Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "AAG Status",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "mssql_dba_custom_alwayson_healthy_ratio[12h]",
     "legendFormat": "__auto"
    },
    {
     "expr": "mssql_dba_custom_alwayson_healthy_ratio[30d]",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Agent Job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "SQL Agent Job ",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(mssql_dba_custom_agent_Jobfailed_result[30m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(mssql_dba_custom_agent_Jobfailed_result[30d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}