{
 "title": "Offernet PRD (PostgreSQL)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "OfferNet - PGSQL PRD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database size MB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    datname,\r\n    ROUND(pg_database_size(datname) / (1024.0 * 1024 ), 2) AS size\r\nFROM pg_database\r\nORDER BY pg_database_size(datname) DESC;"
    }
   ]
  },
  {
   "title": "Buffer Hit Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(100.0 * sum(heap_blks_hit)\r\n             / nullif(sum(heap_blks_hit)\r\n                    + sum(heap_blks_read), 0), 2) AS cache_hit_pct\r\nFROM   pg_statio_user_tables;"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(*) FILTER (WHERE state = 'active') AS Active,\r\n    count(*) FILTER (WHERE state = 'idle') AS Idle,\r\n    count(*) AS Total\r\nFROM pg_stat_activity;"
    }
   ]
  },
  {
   "title": "Table(S)",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT schemaname,\r\n       relname,\r\n       pg_size_pretty(pg_total_relation_size(relid))  AS total,\r\n       pg_size_pretty(pg_relation_size(relid))        AS table_only,\r\n       pg_size_pretty(pg_indexes_size(relid))         AS indexes,\r\n       ROUND(pg_total_relation_size(relid)  / (1024.0 * 1024 * 1024), 2)   AS totalSzie\r\nFROM   pg_stat_user_tables\r\nORDER  BY pg_total_relation_size(relid) DESC\r\n"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT pid,\r\n       now() - query_start            AS duration,\r\n       state,\r\n       wait_event_type,\r\n       wait_event,\r\n       left(query, 120)               AS query\r\nFROM   pg_stat_activity\r\nORDER  BY duration desc;"
    }
   ]
  },
  {
   "title": "Missing Indexes",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT relname                          AS table,\r\n       seq_scan,\r\n       seq_tup_read,\r\n       pg_size_pretty(\r\n         pg_total_relation_size(relid)) AS size\r\nFROM   pg_stat_user_tables\r\nWHERE  seq_scan > 100\r\nORDER  BY seq_tup_read DESC\r\nLIMIT  15;"
    }
   ]
  },
  {
   "title": "Unused Indexes",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT schemaname,\r\n       relname       AS table,\r\n       indexrelname  AS index,\r\n       idx_scan      AS scans,\r\n       pg_size_pretty(pg_relation_size(indexrelid)) AS index_size\r\nFROM   pg_stat_user_indexes\r\nWHERE  idx_scan = 0\r\n  AND  schemaname NOT IN ('pg_catalog', 'pg_toast')\r\nORDER  BY pg_relation_size(indexrelid) DESC;"
    }
   ]
  },
  {
   "title": "Longest running transaction",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT pid,\r\n       usename,\r\n       now() - xact_start   AS txn_duration,\r\n       state,\r\n       left(query, 100)     AS last_query\r\nFROM   pg_stat_activity\r\nWHERE  xact_start IS NOT NULL\r\nORDER  BY xact_start\r\nLIMIT  10;"
    }
   ]
  }
 ]
}