{
 "title": "Permissions",
 "tags": [
  "DBA",
  "Security"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "mssql" },
   { "name": "DatabasePattern" },
   {
    "name": "DatabaseName",
    "query": "SELECT DISTINCT DatabaseName FROM Security.DatabasePermission WHERE CheckDateTime < $__timeTo() AND DatabaseName LIKE '%'+'$DatabasePattern'+'%'"
   },
   {
    "name": "LoginName",
    "query": "SELECT DISTINCT LoginName FROM Security.ServerPermission WHERE CheckDateTime < $__timeTo() AND LoginName IS NOT NULL"
   },
   {
    "name": "DatabaseRole",
    "query": "SELECT DISTINCT DatabaseRole FROM Security.DatabasePermission WHERE CheckDateTime < $__timeTo() AND DatabaseRole IS NOT NULL"
   }
  ]
 },
 "panels": [
  {
   "title": "$Datasource Server Permissions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Datasource",
   "targets": [
    {}
   ]
  },
  {
   "title": "Login Has Access",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT LoginName, ServerRole, PermissionName, PermissionState, CheckDateTime\r\nFROM [Security].[ServerPermission]\r\nWHERE 1=1\r\nAND PermissionName = 'CONNECT SQL'\r\nAND LoginName IN ($LoginName)\r\nAND CheckDateTime <= $__timeTo()\r\nAND CheckDateTime >= (SELECT MAX(CheckDateTime)\r\n                      FROM Security.ServerPermission\r\n                      WHERE CheckDateTime <= $__timeTo())"
    }
   ]
  },
  {
   "title": "Additional Server Rights",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT LoginName, PermissionName, PermissionState, CheckDateTime\r\nFROM [Security].[ServerPermission]\r\nWHERE 1=1\r\nAND (PermissionName <> 'CONNECT SQL') \r\nAND LoginName IN ($LoginName)\r\nAND CheckDateTime <= $__timeTo()\r\nAND CheckDateTime >= (SELECT MAX(CheckDateTime)\r\n                      FROM Security.ServerPermission\r\n                      WHERE CheckDateTime <= $__timeTo())"
    }
   ]
  },
  {
   "title": "$Datasource Database Permissions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "Datasource",
   "targets": [
    {}
   ]
  },
  {
   "title": "Database Roles",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT [DatabaseName]\r\n\t,[UserType]\r\n\t,[DatabaseUserName]\r\n\t,[LoginName]\r\n\t,[DatabaseRole]\r\n\t,[CheckDateTime]\r\nFROM [Security].[DatabasePermission]\r\nWHERE (PermissionType <> 'CONNECT'\r\n\tOR PermissionType IS NULL)\r\nAND DatabaseName IN ($DatabaseName)\r\nAND LoginName IN ($LoginName)\r\nAND DatabaseRole IN ($DatabaseRole)\r\nAND CheckDateTime <= $__timeTo()\r\nAND CheckDateTime >= (SELECT MAX(CheckDateTime)\r\n                      FROM Security.DatabasePermission\r\n                      WHERE CheckDateTime <= $__timeTo())"
    }
   ]
  },
  {
   "title": "Specific Database Rights",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT DatabaseName, UserType, LoginName, PermissionType, PermissionState, ObjectType, [Schema], ObjectName, ColumnName, CheckDateTime\r\nFROM [Security].[DatabasePermission]\r\nWHERE (PermissionType <> 'CONNECT'\r\n\tOR PermissionType IS NULL)\r\nAND DatabaseName IN ($DatabaseName)\r\nAND LoginName IN ($LoginName)\r\nAND DatabaseRole IS NULL\r\nAND CheckDateTime <= $__timeTo()\r\nAND CheckDateTime >= (SELECT MAX(CheckDateTime)\r\n                      FROM Security.DatabasePermission\r\n                      WHERE CheckDateTime <= $__timeTo())"
    }
   ]
  }
 ]
}