{
 "title": "Replication Copy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "Datasource",
    "query": "AZFRCER0289\\PRNG,AZFRCER0256\\PRNW,PLER0104\\PXRP,THLR1024\\PXR1,CNT-RXREPP01\\PXRT,CNER0343\\PXRH,THMR2024\\PXRI"
   }
  ]
 },
 "panels": [
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 16, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "Over All Status  ($Datasource)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "IF DB_ID('distribution') IS NOT NULL\r\nBEGIN\r\n    SELECT \r\n       \r\n        max(s.UndelivCmdsInDistDB) AS UndistributedCommands\r\n\r\n    FROM distribution.dbo.MSrepl_transactions t with (nolock)\r\n    JOIN distribution.dbo.MSdistribution_agents a with (nolock)\r\n        ON t.publisher_database_id = a.publisher_database_id\r\n\r\n    LEFT JOIN distribution.dbo.MSdistribution_status s\r\n        ON a.id = s.agent_id\r\n\r\nEND"
    }
   ]
  },
  {
   "title": "Over All Status  ($Datasource)",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 3 },
   "targets": [
    {
     "rawSql": "IF DB_ID('distribution') IS NOT NULL\r\nBEGIN\r\n    SELECT \r\n        SERVERPROPERTY('MachineName') AS ServerName,\r\n        SERVERPROPERTY('InstanceName') AS InstanceName,\r\n        a.publication,\r\n        a.publisher_db,\r\n        a.subscriber_db,\r\n\r\n        -- Latency in seconds since latest transaction entered distribution\r\n        DATEDIFF(SECOND, MAX(t.entry_time), GETDATE()) AS Latency,\r\n\r\n        -- Undistributed commands pending for subscriber\r\n        ISNULL(MAX(s.UndelivCmdsInDistDB),0) AS UndistributedCommands\r\n\r\n    FROM distribution.dbo.MSrepl_transactions t with (nolock)\r\n    JOIN distribution.dbo.MSdistribution_agents a with (nolock)\r\n        ON t.publisher_database_id = a.publisher_database_id\r\n\r\n    LEFT JOIN distribution.dbo.MSdistribution_status s\r\n        ON a.id = s.agent_id\r\n\r\n    GROUP BY\r\n        a.publication,\r\n        a.publisher_db,\r\n        a.subscriber_db\r\nEND"
    }
   ]
  },
  {
   "title": "Agent Status  ($Datasource)",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 10 },
   "targets": [
    {
     "dataset": "AdminSQL",
     "rawSql": "SELECT publisher,\r\npublisher_db,\r\npublication_id,\r\nCASE publication_type\r\n\tWHEN 0 then 'Transactional'\r\n\tWHEN 1 then 'Snapshot'\r\n\tWHEN 2 then 'Merge'\r\nEND AS publication_type_desc,\r\npublication,\r\nCASE agent_type\r\n\tWHEN 1 then 'Snapshot'\r\n\tWHEN 2 then 'Log Reader'\r\n\tWHEN 3 then 'Distribution'\r\n\tWHEN 4 then 'Merge'\r\n\tWHEN 9 then 'Queue Reader'\r\nEND AS agent_type,\r\nagent_name,\r\nCASE status\r\n\tWHEN 1 THEN 'Started'\r\n\tWHEN 2 THEN 'Succeeded'\r\n\tWHEN 3 THEN 'In progress'\r\n\tWHEN 4 THEN 'Idle'\r\n\tWHEN 5 THEN 'Retrying'\r\n\tWHEN 6 THEN 'Failed'\r\nEND AS agent_status,\r\nCASE warning\r\n\tWHEN 1 THEN 'Expiration'\r\n\tWHEN 2 THEN 'Latency'\r\n\tWHEN 4 THEN 'Merge expiration '\r\n\tWHEN 16 THEN 'Merge slow run duration '\r\n\tWHEN 32 THEN 'Merge fast run speed '\r\n\tWHEN 64 THEN 'Merge slow run speed'\r\nEND AS warning\r\nFROM distribution.dbo.MSreplication_monitordata\r\nORDER BY publisher, \r\nagent_type, \r\npublication"
    },
    {
     "dataset": "distribution",
     "rawSql": "SELECT\r\n    GETDATE() as sample_time,\r\n    a.name as agent_name,\r\n    h.runstatus,\r\n    CASE h.runstatus\r\n        WHEN 1 THEN 'Starting'\r\n        WHEN 2 THEN 'Succeeded'\r\n        WHEN 3 THEN 'In progress'\r\n        WHEN 4 THEN 'Idle'\r\n        WHEN 5 THEN 'Retrying'\r\n        WHEN 6 THEN 'Failed'\r\n    END as status_desc,\r\n    h.time,\r\n    h.comments\r\nFROM distribution.dbo.MSlogreader_agents a\r\nOUTER APPLY (\r\n    SELECT TOP 1 *\r\n    FROM distribution.dbo.MSlogreader_history h\r\n    WHERE h.agent_id = a.id\r\n    ORDER BY h.time DESC\r\n) h;"
    },
    {
     "dataset": "distribution",
     "rawSql": "SELECT\r\n    GETDATE() as sample_time,\r\n    a.name,\r\n    a.publisher_db,\r\n    a.subscriber_db,\r\nCASE h.runstatus\r\n        WHEN 1 THEN 'Starting'\r\n        WHEN 2 THEN 'Succeeded'\r\n        WHEN 3 THEN 'In progress'\r\n        WHEN 4 THEN 'Idle'\r\n        WHEN 5 THEN 'Retrying'\r\n        WHEN 6 THEN 'Failed'\r\n    END as status_desc,\r\n    h.delivery_latency,\r\n    h.delivered_commands,\r\n    h.comments\r\nFROM distribution.dbo.MSdistribution_agents a\r\nOUTER APPLY (\r\n    SELECT TOP 1 *\r\n    FROM distribution.dbo.MSdistribution_history h\r\n    WHERE h.agent_id = a.id\r\n    ORDER BY h.time DESC\r\n) h;\r\n"
    }
   ]
  },
  {
   "title": "Agents History ($Datasource)",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 16 },
   "targets": [
    {
     "rawSql": "IF DB_ID('distribution') IS NOT NULL\r\nBEGIN\r\nSELECT 'SnapShot' as [SnapShot]\r\n,[comments],[start_time]\r\n  FROM [distribution].[dbo].[MSsnapshot_history] \r\n  where\r\n  comments in ('Starting agent.','Initializing') \r\nEND"
    },
    {
     "dataset": "AdminSQL",
     "rawSql": "IF DB_ID('distribution') IS NOT NULL\r\nBEGIN\r\nSELECT [runstatus]\r\n      ,[start_time]\r\n       ,[duration]\r\n      ,[comments]\r\n      ,[error_id]\r\n  FROM [distribution].[dbo].[MSlogreader_history] where error_id<>0\r\n  END\r\n  "
    },
    {
     "dataset": "AdminSQL",
     "rawSql": "IF DB_ID('distribution') IS NOT NULL\r\nBEGIN\r\nSELECT [start_time]\r\n       ,[duration]\r\n      ,[comments]\r\n      ,[error_id]\r\n  FROM [distribution].[dbo].[MSdistribution_history] where error_id<>0\r\n  END\r\n"
    }
   ]
  },
  {
   "title": "Articles  ($Datasource)",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "repeat": "Datasource",
   "targets": [
    {
     "rawSql": "IF DB_ID('distribution') IS NOT NULL\r\nBEGIN\r\n    SELECT\r\n    p.publisher_db,\r\n    p.publication,\r\n    a.article,\r\n    a.source_owner AS schema_name,\r\n    a.source_object,\r\n    a.destination_owner,\r\n    a.destination_object,\r\n    a.article_id\r\nFROM distribution.dbo.MSarticles a\r\nJOIN distribution.dbo.MSpublications p\r\n    ON a.publication_id = p.publication_id\r\nORDER BY\r\n    p.publisher_db,\r\n    p.publication,\r\n    a.article;\r\nEND"
    }
   ]
  }
 ]
}