{
 "title": "SQL Server - Overview",
 "tags": [ "DBA" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Datasource",
    "query": "SELECT ServerName \nFROM Inventory.ServerList \nWHERE\nSupportGroup  LIKE \n  CASE\n    WHEN $__user = 18 THEN 'DXC%'\n    ELSE 'D%' END"
   }
  ]
 },
 "panels": [
  {
   "title": "SQL Blocking New ( Frequent Blockings )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Most frequent blocked process",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "dataset": "ASSISTEDCONTROL",
       "rawSql": "DECLARE @xe_path NVARCHAR(260)\r\n\r\nSELECT \r\n    @xe_path=target_data_xml.value('(EventFileTarget/File/@name)[1]', 'nvarchar(4000)') \r\nFROM sys.dm_xe_sessions AS s\r\nJOIN sys.dm_xe_session_targets AS t\r\n    ON s.address = t.event_session_address\r\nCROSS APPLY (SELECT CAST(t.target_data AS XML)) AS x(target_data_xml)\r\nWHERE t.target_name = 'event_file' and s.name like '%BlockedProcessReport%';\r\n\r\nSELECT \r\n    event_data = CAST(event_data AS XML)\r\n\tINTO #BlockedEvents\r\nFROM sys.fn_xe_file_target_read_file(\r\n    @xe_path,\r\n    NULL, NULL, NULL);\r\n\r\n;WITH BlockRelations AS\r\n(\r\n    SELECT\r\n        Event_Data.value('(event/data[@name=\"database_name\"]/value)[1]', 'sysname') AS DatabaseName,\r\n\r\n        -- Infos Blocked\r\n        BP.value('@spid', 'int')                 AS BlockedSPID,\r\n        BP.value('@hostname', 'nvarchar(128)')   AS BlockedHost,\r\n        BP.value('@loginname', 'nvarchar(128)')  AS BlockedLogin,\r\n        BP.value('@clientapp', 'nvarchar(256)')  AS BlockedApp,\r\n        BP.value('inputbuf[1]', 'nvarchar(max)') AS BlockedSQL,\r\n\r\n        -- Infos Blocking\r\n        BL.value('@spid', 'int')                 AS BlockingSPID,\r\n        BL.value('@hostname', 'nvarchar(128)')   AS BlockingHost,\r\n        BL.value('@loginname', 'nvarchar(128)')  AS BlockingLogin,\r\n        BL.value('@clientapp', 'nvarchar(256)')  AS BlockingApp,\r\n        BL.value('inputbuf[1]', 'nvarchar(max)') AS BlockingSQL\r\n    FROM #BlockedEvents\r\n    CROSS APPLY Event_Data.nodes('/event') AS E(X)\r\n    CROSS APPLY E.X.nodes('data[@name=\"blocked_process\"]/value/blocked-process-report/blocked-process/process') AS BPNode(BP)\r\n    CROSS APPLY E.X.nodes('data[@name=\"blocked_process\"]/value/blocked-process-report/blocking-process/process') AS BLNode(BL)\r\n)\r\nSELECT TOP 20\r\n    COUNT(*) AS NbOccurrences,\r\n    DatabaseName,\r\n\r\n    -- Identit  du bloqu \r\n    BlockedLogin,\r\n    BlockedHost,\r\n    BlockedApp,\r\n    BlockedSQL,\r\n\r\n    -- Identit  du bloqueur\r\n    BlockingLogin,\r\n    BlockingHost,\r\n    BlockingApp,\r\n    BlockingSQL\r\nFROM BlockRelations\r\nGROUP BY DatabaseName,\r\n         BlockedLogin, BlockedHost, BlockedApp, BlockedSQL,\r\n         BlockingLogin, BlockingHost, BlockingApp, BlockingSQL\r\nORDER BY COUNT(*) DESC;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource Configurations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Configurations",
     "type": "table",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 2 },
     "targets": [
      {
       "dataset": "ASSISTEDCONTROL",
       "rawSql": "select Name,Value,Value_in_use, Description from sys.configurations where name in ('max degree of parallelism',\r\n'max server memory (MB)',\r\n'min server memory (MB)',\r\n'network packet size (B)',\r\n'remote query timeout (s)',\r\n'cost threshold for parallelism') order by Name"
      }
     ]
    },
    {
     "title": "SQL Configurations",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "repeat": "Datasource",
     "targets": [
      {
       "dataset": "ASSISTEDCONTROL",
       "rawSql": "SELECT * FROM [AdminSQLCentral].[dbo].[Server_SA] A\r\nLEFT OUTER  JOIN \r\n[Inventory].[ServerList] B ON substring(b.Servername,1,charindex('\\',b.ServerName)-1)  = A.SERVER_NAME \r\nWHERE B.ServerName IN ($Datasource)"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource Live",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active Processes",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "EXEC sp_WhoIsActive\r\n    @filter = '',\r\n    @filter_type = 'session',\r\n    @not_filter = '',\r\n    @not_filter_type = 'session',\r\n    @show_own_spid = 0,\r\n    @show_system_spids = 0,\r\n    @show_sleeping_spids = 1,\r\n    @get_full_inner_text = 0,\r\n    @get_plans = 0,\r\n    @get_outer_command = 0,\r\n    @get_transaction_info = 0,\r\n    @get_task_info = 0,\r\n    @get_locks = 0,\r\n    @get_avg_time = 0,\r\n    @get_additional_info = 0,\r\n    @find_block_leaders = 1,\r\n    @delta_interval = 0,\r\n    @output_column_list = '[dd%][session_id][login_name][wait_info][database_name][program_name][sql_text]',\r\n    @sort_order = '[start_time] ASC',\r\n    @format_output = 1,\r\n    @destination_table = '',\r\n    @return_schema = 0,\r\n    @schema = NULL,\r\n    @help = 0"
      }
     ]
    },
    {
     "title": "Blocking Processes",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT t1.resource_type AS [lock type], DB_NAME(resource_database_id) AS [database],\r\nt1.resource_associated_entity_id AS [blk object],t1.request_mode AS [lock req],  --- lock requested\r\nt1.request_session_id AS [waiter sid], t2.wait_duration_ms AS [wait time],       -- spid of waiter  \r\n(SELECT [text] FROM sys.dm_exec_requests AS r WITH (NOLOCK)                      -- get sql for waiter\r\nCROSS APPLY sys.dm_exec_sql_text(r.[sql_handle]) \r\nWHERE r.session_id = t1.request_session_id) AS [waiter_batch],\r\n(SELECT SUBSTRING(qt.[text],r.statement_start_offset/2, \r\n    (CASE WHEN r.statement_end_offset = -1 \r\n    THEN LEN(CONVERT(nvarchar(max), qt.[text])) * 2 \r\n    ELSE r.statement_end_offset END - r.statement_start_offset)/2) \r\nFROM sys.dm_exec_requests AS r WITH (NOLOCK)\r\nCROSS APPLY sys.dm_exec_sql_text(r.[sql_handle]) AS qt\r\nWHERE r.session_id = t1.request_session_id) AS [waiter_stmt],\t\t\t\t\t-- statement blocked\r\nt2.blocking_session_id AS [blocker sid],\t\t\t\t\t\t\t\t\t\t-- spid of blocker\r\n(SELECT [text] FROM sys.sysprocesses AS p\t\t\t\t\t\t\t\t\t\t-- get sql for blocker\r\nCROSS APPLY sys.dm_exec_sql_text(p.[sql_handle]) \r\nWHERE p.spid = t2.blocking_session_id) AS [blocker_stmt]\r\nFROM sys.dm_tran_locks AS t1 WITH (NOLOCK)\r\nINNER JOIN sys.dm_os_waiting_tasks AS t2 WITH (NOLOCK)\r\nON t1.lock_owner_address = t2.resource_address OPTION (RECOMPILE);"
      }
     ]
    },
    {
     "title": "Head Blocker",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "SET NOCOUNT ON\r\n\r\nSELECT SPID, BLOCKED, REPLACE (REPLACE (T.TEXT, CHAR(10), ' '), CHAR (13), ' ' ) AS BATCH\r\nINTO #T\r\nFROM sys.sysprocesses R CROSS APPLY sys.dm_exec_sql_text(R.SQL_HANDLE) T\r\n\r\n;WITH BLOCKERS (SPID, BLOCKED, LEVEL, BATCH)\r\nAS\r\n(\r\nSELECT SPID,\r\nBLOCKED,\r\nCAST (REPLICATE ('0', 4-LEN (CAST (SPID AS VARCHAR))) + CAST (SPID AS VARCHAR) AS VARCHAR (1000)) AS LEVEL,\r\nBATCH FROM #T R\r\nWHERE (BLOCKED = 0 OR BLOCKED = SPID)\r\nAND EXISTS (SELECT * FROM #T R2 WHERE R2.BLOCKED = R.SPID AND R2.BLOCKED <> R2.SPID)\r\nUNION ALL\r\nSELECT R.SPID,\r\nR.BLOCKED,\r\nCAST (BLOCKERS.LEVEL + RIGHT (CAST ((1000 + R.SPID) AS VARCHAR (100)), 4) AS VARCHAR (1000)) AS LEVEL,\r\nR.BATCH FROM #T AS R\r\nINNER JOIN BLOCKERS ON R.BLOCKED = BLOCKERS.SPID WHERE R.BLOCKED > 0 AND R.BLOCKED <> R.SPID\r\n)\r\nSELECT N'    ' + REPLICATE (N'|         ', LEN (LEVEL)/4 - 1) +\r\nCASE WHEN (LEN(LEVEL)/4 - 1) = 0\r\nTHEN 'HEAD -  '\r\nELSE '|------  ' END\r\n+ CAST (SPID AS NVARCHAR (10)) + N' ' + BATCH AS BLOCKING_TREE\r\nFROM BLOCKERS ORDER BY LEVEL ASC\r\n\r\nDROP TABLE #T\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT DATEDIFF(MINUTE,sqlserver_start_time,GETUTCDATE()) FROM sys.dm_os_sys_info;"
      }
     ]
    },
    {
     "title": "CPU Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT cpu_count AS [Logical CPU Count]\r\nFROM sys.dm_os_sys_info WITH (NOLOCK) OPTION (RECOMPILE);"
      }
     ]
    },
    {
     "title": "Minimum SQL Server Memory",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
     "targets": [
      {
       "rawSql": "SELECT getdate() AS time, CAST(value_in_use AS INT) AS Value\r\nFROM sys.configurations WITH (NOLOCK)\r\nWHERE name = 'min server memory (MB)'\r\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Maximum SQL Server Memory",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT getdate() AS time, CAST(value_in_use AS INT) AS Value\r\nFROM sys.configurations WITH (NOLOCK)\r\nWHERE name = 'max server memory (MB)'\r\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Total OS Memory",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT total_physical_memory_kb \nFROM sys.dm_os_sys_memory"
      }
     ]
    },
    {
     "title": "Available OS Memory",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT available_physical_memory_kb \nFROM sys.dm_os_sys_memory"
      }
     ]
    },
    {
     "title": "Database Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) FROM sys.databases WHERE database_id > 4"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT ec.client_net_address, es.[program_name], es.[host_name], es.login_name, \r\nCOUNT(ec.session_id) AS [connection count] \r\nFROM sys.dm_exec_sessions AS es WITH (NOLOCK) \r\nINNER JOIN sys.dm_exec_connections AS ec WITH (NOLOCK) \r\nON es.session_id = ec.session_id \r\nGROUP BY ec.client_net_address, es.[program_name], es.[host_name], es.login_name  \r\nORDER BY [connection count] DESC  OPTION (RECOMPILE);"
      }
     ]
    },
    {
     "title": "User Connections (Performance Counter)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT  CheckDateTime as time,\r\n        CounterName,\r\n\t\tCounterValue AS Value\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('User Connections')\r\n\tORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Overview",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 24 },
     "targets": [
      {
       "rawSql": "SELECT S.Severity\r\n\t , ISNULL([Count], 0) AS [Count]\r\nFROM\r\n(\r\n\tSELECT Severity\r\n\t\t , COUNT(DISTINCT name) AS [Count]\r\n\tFROM Monitoring.Alert\r\n\tWHERE $__timeFilter(CreateDateTime)\r\n\tGROUP BY Severity\r\n) AS A\r\nRIGHT JOIN Report.V_Severity AS S ON A.Severity = S.Severity"
      }
     ]
    },
    {
     "title": "Alert",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 19, "x": 5, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT CreateDateTime AS time, \r\n       Name, \r\n       COUNT(*) AlertCount\r\nFROM [Monitoring].[Alert]\r\nWHERE $__timeFilter(CreateDateTime)\r\nGROUP BY CreateDateTime,Name \r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Process Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT CheckDateTime AS time\r\n  ,SQLProcessUtilization\r\n  ,OtherProcessUtilization\r\n\t,SQLProcessUtilization+OtherProcessUtilization AS TotalProcessUtilization\r\n--\t,SystemIdle\r\nFROM Archive.ProcessUtilization\r\nWHERE $__timeFilter(CheckDateTime)\r\n"
      }
     ]
    },
    {
     "title": "Schedulers",
     "type": "timeseries",
     "description": "Task > 10 = Blocking/Deadlocking  \nRunnable > 1 = CPU Pressure  \nPendingDiskIO > 1 = Disk Pressure  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT CheckDateTime AS time\r\n\t,[AverageTaskCount]\r\n\t,[AverageRunnableTaskCount]\r\n\t,[AveragePendingDiskIOCount]\r\nFROM Archive.Schedulers\r\nWHERE $__timeFilter(CheckDateTime)\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage (KB)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "rawSql": "SELECT  CheckDateTime as time,\r\n        CounterName,\r\n\t\tCounterValue AS Value\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Total Server Memory (KB)','Lock Memory (KB)','Connection Memory (KB)','Database Cache Memory (KB)')\r\n\tORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Lazy writes/sec",
     "type": "timeseries",
     "description": "Should be less than 2",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Lazy writes/sec')\r\n)\r\nSELECT a.CheckDateTime AS time,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue])/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS CounterValue\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]\r\nORDER BY time ASC\r\n"
      }
     ]
    },
    {
     "title": "Memory Grants Pending",
     "type": "timeseries",
     "description": "Should be 0",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT  CheckDateTime as time,\r\n        CounterName,\r\n\t\tCounterValue AS Value\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Memory Grants Pending')\r\n\tORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Page Life Expectancy",
     "type": "timeseries",
     "description": "Calculated PLE per 4GB, threshold fixed at 300 seconds",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT CheckDateTime as time,\nInstanceName,\n(PageLifeExpectancyDynamic) AS Value\nFROM Archive.V_PageLifeExpectancy\nWHERE $__timeFilter(CheckDateTime)\nORDER BY time ASC\n"
      }
     ]
    },
    {
     "title": "Free list stalls/sec",
     "type": "timeseries",
     "description": "Should be less than 20",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Free list stalls/sec')\r\n)\r\nSELECT a.CheckDateTime AS time,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue])/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS CounterValue\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]\r\nORDER BY time ASC\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Drive Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": ";WITH DriveIOLatency AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\t    CheckDateTime,\r\n        LEFT(UPPER(PhysicalName), 1) AS Drive,\r\n        SUM(io_stall_read_ms) AS io_stall_read_ms,\r\n        SUM(io_stall_write_ms) AS io_stall_write_ms,\r\n        SUM(num_of_reads) AS num_of_reads,\r\n\t\tSUM(num_of_writes) AS num_of_writes\r\n    FROM [Archive].[FileStatistics]\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n    GROUP BY CheckDateTime, LEFT(UPPER(PhysicalName), 1)\r\n)\r\nSELECT a.CheckDateTime AS time,\r\n\t     a.Drive,\r\n       CASE WHEN(a.num_of_reads-aPrior.num_of_reads) = 0 THEN 0\r\n       ELSE(a.io_stall_read_ms-aPrior.io_stall_read_ms)*1.0/(a.num_of_reads-aPrior.num_of_reads)*1.0 END AS ReadLatency,\r\n       CASE WHEN(a.num_of_writes-aPrior.num_of_writes) = 0 THEN 0\r\n       ELSE(a.io_stall_write_ms-aPrior.io_stall_write_ms)*1.0/(a.num_of_writes-aPrior.num_of_writes)*1.0 END AS WriteLatency\r\nFROM DriveIOLatency a\r\nINNER JOIN DriveIOLatency aPrior\r\nON a.Drive = aPrior.Drive\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.num_of_reads >= aPrior.num_of_reads\r\nAND a.num_of_writes >= aPrior.num_of_writes\r\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "R/W IOPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH DriveIOIOPS AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\t    CheckDateTime,\r\n        LEFT(UPPER(PhysicalName), 1) AS Drive,\r\n        SUM(num_of_reads) AS num_of_reads,\r\n\t\tSUM(num_of_writes) AS num_of_writes\r\n    FROM [Archive].[FileStatistics]\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n    GROUP BY CheckDateTime, LEFT(UPPER(PhysicalName), 1)\r\n)\r\nSELECT  a.CheckDateTime AS time,\r\n\t      a.Drive,\r\n        (a.num_of_reads - aPrior.num_of_reads)*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS ReadIOPS,\r\n        (a.num_of_writes - aPrior.num_of_writes)*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS WriteIOPS\r\nFROM DriveIOIOPS a\r\nINNER JOIN DriveIOIOPS aPrior\r\nON a.Drive = aPrior.Drive\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.num_of_reads >= aPrior.num_of_reads\r\nAND a.num_of_writes >= aPrior.num_of_writes\r\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "R/W Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "rawSql": ";WITH DriveIOThroughput AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\t    CheckDateTime,\r\n        LEFT(UPPER(PhysicalName), 1) AS Drive,\r\n        SUM(num_of_bytes_read) AS num_of_bytes_read,\r\n\t\tSUM(num_of_bytes_written) AS num_of_bytes_written\r\n    FROM [Archive].[FileStatistics]\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n    GROUP BY CheckDateTime, LEFT(UPPER(PhysicalName), 1)\r\n)\r\nSELECT  a.CheckDateTime AS time,\r\n\t      a.Drive,\r\n        (a.num_of_bytes_read - aPrior.num_of_bytes_read)/1024/1024*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS ReadThroughputMBPS,\r\n        (a.num_of_bytes_written - aPrior.num_of_bytes_written)/1024/1024*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS WriteThroughputMBPS\r\nFROM DriveIOThroughput a\r\nINNER JOIN DriveIOThroughput aPrior\r\nON a.Drive = aPrior.Drive\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.num_of_bytes_read >= aPrior.num_of_bytes_read\r\nAND a.num_of_bytes_written >= aPrior.num_of_bytes_written\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "Datasource",
   "targets": [
    {}
   ]
  },
  {
   "title": "CommandLog (BACKUP_DATABASE)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT [StartTime] AS time,\r\nDatabaseName,\r\nDATEDIFF(SECOND,StartTime,EndTime) Value\r\n  FROM msdb.[dbo].[CommandLog]\r\n  WHERE 1=1\r\nAND CommandType IN ('BACKUP_DATABASE')\r\nAND $__timeFilter(StartTime)\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "CommandLog (DBCC_CHECKDB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT [StartTime] AS time,\r\nDatabaseName,\r\nDATEDIFF(SECOND,StartTime,EndTime) Value\r\n  FROM MSDB.[dbo].[CommandLog]\r\n  WHERE 1=1\r\nAND CommandType IN ('DBCC_CHECKDB')\r\n--AND Command LIKE '%DIFF%'\r\nAND $__timeFilter(StartTime)\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "CommandLog (UPDATE_STATISTICS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT DATEADD(minute,DATEDIFF(minute,'2000-01-01',StartTime)/5*5,'2000-01-01') AS time,\r\nDatabaseName,\r\nDATEDIFF(SECOND,MIN(StartTime),MAX(EndTime)) Value\r\n  FROM MSDB.[dbo].[CommandLog]\r\n  WHERE 1=1\r\nAND CommandType IN ('UPDATE_STATISTICS')\r\n--AND Command LIKE '%DIFF%'\r\nAND $__timeFilter(StartTime)\r\nGROUP BY DATEADD(minute,DATEDIFF(minute,'2000-01-01',StartTime)/5*5,'2000-01-01'),DatabaseName\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "CommandLog (ALTER_INDEX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT DATEADD(minute,DATEDIFF(minute,'2000-01-01',StartTime)/5*5,'2000-01-01') AS time,\r\nDatabaseName,\r\nDATEDIFF(SECOND,MIN(StartTime),MAX(EndTime)) Value\r\n  FROM MSDB.[dbo].[CommandLog]\r\n  WHERE 1=1\r\nAND CommandType IN ('ALTER_INDEX')\r\n--AND Command LIKE '%DIFF%'\r\nAND $__timeFilter(StartTime)\r\nGROUP BY DATEADD(minute,DATEDIFF(minute,'2000-01-01',StartTime)/5*5,'2000-01-01'),DatabaseName\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Maintenance Jobs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "\t   SELECT sJOB.name AS JobName\r\n\t\t, msdb.dbo.agent_datetime(run_date, run_time) AS RunStartTime\r\n\t\t, ( run_duration / 10000 * 60 * 60 ) + ( run_duration / 100 % 100 * 60 ) + ( run_duration % 100 ) AS RunDuration --seconds\r\n\t\t\t, sJOBH.run_status AS RunStatus\r\n\t\t\t--, CASE WHEN sJOBH.run_status = 0 THEN 'Failed'\r\n\t\t\t--\t   WHEN sJOBH.run_status = 1 THEN 'Succeeded'\r\n\t\t\t--\t   WHEN sJOBH.run_status = 2 THEN 'Retry'\r\n\t\t\t--\t   WHEN sJOBH.run_status = 3 THEN 'Canceled'\r\n\t\t\t--\t   WHEN sJOBH.run_status = 4 THEN 'In Progress'\r\n\t\t\t--END AS RunStatus\r\n\t   FROM msdb.dbo.sysjobs AS sJOB\r\n\t   LEFT JOIN\r\n\t   (\r\n\t\t   SELECT job_id\r\n\t\t\t\t, step_name\r\n\t\t\t\t, run_date\r\n\t\t\t\t, run_time\r\n\t\t\t\t, run_status\r\n\t\t\t\t, run_duration\r\n\t\t\t\t, message\r\n\t\t\t\t, ROW_NUMBER() OVER(PARTITION BY job_id\r\n\t\t\t\t\t\t\t\t\t\t\t   , step_id\r\n\t\t\t\t  ORDER BY run_date DESC\r\n\t\t\t\t\t\t , run_time DESC) AS RowNumber\r\n\t\t   FROM msdb.dbo.sysjobhistory\r\n\t\t   WHERE step_id <> 0\r\n\t   ) AS sJOBH ON sJOB.job_id = sJOBH.job_id AND \r\n\t\t\t\t\t sJOBH.RowNumber = 1\r\n\t\r\n\t   WHERE sJOB.enabled = 1 AND \r\n\t   ( sJOB.name LIKE 'DBA_SystemDatabaseBackup%'\r\n\t   OR sJOB.name LIKE 'DBA_UserDatabaseBackup%'\r\n\t   OR sJOB.name LIKE 'DBA_UpdateStatistics'\r\n\t   OR sJOB.Name LIKE 'DBA_SystemDatabaseIntegrityCheck'\r\n\t   OR sJOB.Name LIKE 'DBA_UserDatabaseIntegrityCheck'\r\n\t   OR sJOB.Name LIKE 'DBA_IndexMaintenance'\r\n\t   )\r\n\t\t\t OPTION(RECOMPILE);"
    }
   ]
  },
  {
   "title": "$Datasource Wait Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Waits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": ";WITH WaitStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        WaitType,\r\n\t\tWaitCount,\r\n\t\tWait_Seconds\r\n    FROM [Archive].WaitStatistics\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n)\r\nSELECT a.CheckDateTime AS time,\r\n\t   a.WaitType,\r\n\t   --(a.WaitCount - aPrior.WaitCount) AS WaitCountDelta,\r\n       (a.[Wait_Seconds] - aPrior.[Wait_Seconds]) AS Value\r\nFROM WaitStatistics a\r\nINNER JOIN WaitStatistics aPrior\r\nON a.WaitType = aPrior.WaitType\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.WaitCount >= aPrior.WaitCount\r\nORDER BY time ASC\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "Avg Waits",
     "type": "timeseries",
     "description": "Waits/WaitCount",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": ";WITH WaitStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n    WaitType,\r\n\t\tWaitCount,\r\n\t\tWait_Seconds\r\n    FROM [Archive].WaitStatistics\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n)\r\nSELECT a.CheckDateTime AS time,\r\n\t   a.WaitType,\r\n    (a.[Wait_Seconds] - aPrior.[Wait_Seconds]) / NULLIF((a.[WaitCount] - aPrior.[WaitCount]),0) AS Value\r\nFROM WaitStatistics a\r\nINNER JOIN WaitStatistics aPrior\r\nON a.WaitType = aPrior.WaitType\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.WaitCount >= aPrior.WaitCount\r\nORDER BY time ASC\r\n"
      }
     ]
    },
    {
     "title": "Signal Waits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": ";WITH WaitStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        WaitType,\r\n\t\tWaitCount,\r\n\t\tWait_Seconds,\r\n\t\tSignal_Seconds\r\n    FROM [Archive].WaitStatistics\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n)\r\nSELECT a.CheckDateTime AS time,\r\n\t   a.WaitType,\r\n\t   CAST(100.0 * SUM(a.Signal_Seconds-aPrior.Signal_Seconds) / NULLIF(SUM(a.Wait_Seconds-aPrior.Wait_Seconds),0) AS NUMERIC(20, 2)) AS [%signal (cpu) waits],\r\n     CAST(100.0 * nullif(SUM((a.Wait_Seconds-aPrior.Wait_Seconds) - (a.Signal_Seconds-aPrior.Signal_Seconds)),0) / nullif(SUM((a.Wait_Seconds-aPrior.Wait_Seconds)),0) AS NUMERIC(20, 2)) AS [%resource waits]\r\nFROM WaitStatistics a\r\nINNER JOIN WaitStatistics aPrior\r\nON a.WaitType = aPrior.WaitType\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.WaitCount >= aPrior.WaitCount\r\nGROUP BY a.CheckDateTime,a.WaitType\r\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Signal Waits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": ";WITH WaitStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n    WaitType,\r\n\t\tWaitCount,\r\n\t\tWait_Seconds,\r\n\t\tSignal_Seconds\r\n    FROM [Archive].WaitStatistics\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n)\r\nSELECT a.CheckDateTime AS time,\r\n\t   CAST(100.0 * SUM(a.Signal_Seconds-aPrior.Signal_Seconds) / NULLIF(SUM(a.Wait_Seconds-aPrior.Wait_Seconds),0) AS NUMERIC(20, 2)) AS [%signal (cpu) waits],\r\n     CAST(100.0 * SUM((a.Wait_Seconds-aPrior.Wait_Seconds) - (a.Signal_Seconds-aPrior.Signal_Seconds)) / SUM((a.Wait_Seconds-aPrior.Wait_Seconds)) AS NUMERIC(20, 2)) AS [%resource waits]\r\nFROM WaitStatistics a\r\nINNER JOIN WaitStatistics aPrior\r\nON a.WaitType = aPrior.WaitType\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.WaitCount >= aPrior.WaitCount\r\nGROUP BY a.CheckDateTime\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource SQL Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SQL Statistics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Batch Requests/sec',\r\n                         'SQL Compilations/sec',\r\n                         'SQL Re-Compilations/sec')\r\n)\r\nSELECT a.CheckDateTime AS time,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue])\r\n\t   /\r\n\t   CASE WHEN DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) = 0 THEN 1 ELSE DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) END AS CounterValue\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]\r\nORDER BY time ASC\r\n"
      }
     ]
    },
    {
     "title": "Page Splits/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Page Splits/sec')\r\n)\r\nSELECT a.CheckDateTime AS time,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue])/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS CounterValue\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]\r\nORDER BY time ASC\r\n"
      }
     ]
    },
    {
     "title": "Forwarded Records/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Forwarded Records/sec')\r\n)\r\nSELECT a.CheckDateTime AS time,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue])/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS CounterValue\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]\r\nORDER BY time ASC\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Free Space Less Than 20%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT CheckDateTime AS time, \n       DriveLetter,\n       (TotalSizeMB - (TotalSizeMB - FreeSizeMB))*1.0/TotalSizeMB * 100.0 AS [Free%]\nFROM Archive.DriveSize\nWHERE 1=1\nAND $__timeFilter(CheckDateTime)\nAND (TotalSizeMB - (TotalSizeMB - FreeSizeMB))*1.0/TotalSizeMB * 100.0 < 20\nORDER BY time ASC\n\n"
      }
     ]
    },
    {
     "title": "Used Space",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "rawSql": "SELECT CheckDateTime AS time, \n       DriveLetter,\n       TotalSizeMB - FreeSizeMB AS UsedSizeMB\nFROM Archive.DriveSize\nWHERE 1=1\nAND $__timeFilter(CheckDateTime)\nORDER BY time ASC\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource Blocking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Processes blocked (performance counter)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT  CheckDateTime as time,\r\n        CounterName,\r\n\t\tCounterValue AS Value\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Processes blocked') \r\n\tORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Processes Blocked (Extended Events)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD(MINUTE,DATEDIFF(MINUTE,'2000-01-01',EventTimeStamp)/15*15,'2000-01-01') AS time, \n       SUM(DurationMS/1000) AS Duration,\n       SUM(TotalBlockCount) AS TotalBlockCount\nFROM Archive.BlockedProcessReport\nWHERE 1=1\nAND $__timeFilter(CheckDateTime)\nGROUP BY DATEADD(MINUTE,DATEDIFF(MINUTE,'2000-01-01',EventTimeStamp)/15*15,'2000-01-01')\nORDER BY time ASC\n\n"
      }
     ]
    },
    {
     "title": "Processes Blocked Details",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT EventTimeStamp,\n       TotalBlockCount,\n       BlockedProcess,\n       BlockingProcess,\n       BlockedClientApp,\n       BlockedHostName,\n       BlockedLoginName,\n       BlockedIsolationLevel,\n       BlockingClientApp,\n       BlockingHostName,\n       BlockingLoginName,\n       BlockingIsolationLevel\nFROM Archive.BlockedProcessReport\nWHERE 1=1\nAND $__timeFilter(CheckDateTime)\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource Deadlock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Locks Performance Counter",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Number of Deadlocks/sec',\r\n\t\t\t\t\t\t\t'Lock Timeouts (timeout > 0)/sec')\r\n)\r\nSELECT a.CheckDateTime AS time,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue])/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS Value\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]\r\nORDER BY time ASC\r\n"
      }
     ]
    },
    {
     "title": "Deadlocks (Extended Events)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD(MINUTE,DATEDIFF(MINUTE,'2000-01-01',EventTimeStamp)/15*15,'2000-01-01') AS time, \n       COUNT(*) AS DeadlockCount\nFROM Archive.XMLDeadlockReport\nWHERE 1=1\nAND $__timeFilter(EventTimeStamp)\nGROUP BY DATEADD(MINUTE,DATEDIFF(MINUTE,'2000-01-01',EventTimeStamp)/15*15,'2000-01-01')\nORDER BY time ASC\n\n"
      }
     ]
    },
    {
     "title": "Deadlocks by Object",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD(MINUTE,DATEDIFF(MINUTE,'2000-01-01',EventTimeStamp)/15*15,'2000-01-01') AS time, \n       LockedObject,\n       COUNT(*) AS DeadlockCount\nFROM Archive.XMLDeadlockReportShredded\nWHERE 1=1\nAND $__timeFilter(EventTimeStamp)\nGROUP BY DATEADD(MINUTE,DATEDIFF(MINUTE,'2000-01-01',EventTimeStamp)/15*15,'2000-01-01'),LockedObject\nORDER BY time ASC\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource Error Reported",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Error Reported",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD(MINUTE,DATEDIFF(MINUTE,'2000-01-01',EventTimeStamp)/15*15,'2000-01-01') AS time, \n       CAST(ErrorNumber AS VARCHAR(5)) AS Error,\n       CAST(Severity AS VARCHAR(2)) AS Severity,\n       CAST(ErrorMessage AS VARCHAR(50)) AS ErrorMessage,\n       COUNT(*) AS Value\nFROM Archive.ErrorReported E\nWHERE 1=1\nAND $__timeFilter(EventTimeStamp)\nGROUP BY DATEADD(MINUTE,DATEDIFF(MINUTE,'2000-01-01',EventTimeStamp)/15*15,'2000-01-01'), CAST(ErrorNumber AS VARCHAR(5)), CAST(Severity AS VARCHAR(2)),CAST(ErrorMessage AS VARCHAR(50))\nORDER BY time ASC\n\n"
      }
     ]
    },
    {
     "title": "Error Reported Details",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT EventTimeStamp, \n       ErrorNumber,\n       Severity,\n       ErrorMessage,\n       [SQLText],\n       [ClientAppName], \n       [ClientHostName], \n       [DatabaseName], \n       [ServerPrincipalName]\nFROM Archive.ErrorReported E\nWHERE 1=1\nAND $__timeFilter(EventTimeStamp)\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource User/Group Modifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "User / Group - Modification's ",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "dataset": "ITE_DBA_ADMIN_DB",
       "rawSql": "SELECT [Event_Time]\r\n      ,[Login]\r\n      ,[RoleName]\r\n      ,[ApplicationName]\r\n      ,[HostName]\r\n      ,[LogonName]\r\n      ,[SessionLogonName]\r\n      ,[SQL_Txt]\r\n  FROM [dbo].[DBA_UserChanges] order by event_time "
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource TCP Port",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Port in use",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "AdminSQLCentral",
       "rawSql": "SELECT\r\n  distinct local_tcp_port as value\r\nFROM sys.dm_exec_connections where local_tcp_port is not null"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource Backup Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backup Details",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "dataset": "ASSISTEDCONTROL",
       "rawSql": "Select *, \r\ncase  \r\nwhen DATEDIFF(DAY,GETDATE(),A.Last_Backup)<0 then 1\r\nwhen DATEDIFF(DAY,GETDATE(),A.Last_Backup)=0 then 0\r\nend\r\nDateDiff FROM\r\n(\r\n\tSELECT DB.name AS Database_Name\r\n\t,MAX(DB.recovery_model_desc) AS Recovery_Model\r\n\t,MAX(BS.backup_start_date) AS Last_Backup\r\n\t,MAX(CASE WHEN BS.type = 'D'\r\n\tTHEN BS.backup_start_date END)\r\n\tAS Last_Full_backup,\r\n\tMAX(CASE WHEN BS.type = 'I'\r\n\tTHEN BS.backup_start_date END)\r\n\tAS Last_Differential_backup\r\n\t,MAX(CASE WHEN BS.type = 'L'\r\n\tTHEN BS.backup_start_date END)\r\n\tAS Last_Log_backup\r\n\tFROM sys.databases AS DB\r\n\tLEFT JOIN\r\n\tmsdb.dbo.backupset AS BS\r\n\tON BS.database_name = DB.name\r\n\tWHERE ISNULL(BS.is_damaged, 0) = 0\r\n\tGROUP BY DB.name\r\n ) AS A\r\n WHERE A.Database_Name<>'tempdb'\r\n \tORDER BY Last_Backup desc"
      }
     ]
    }
   ]
  }
 ]
}