{
 "title": "SQL Server Connections",
 "tags": [
  "Databases",
  "DBA"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Datasource",
    "query": "SELECT ServerName \nFROM Inventory.ServerList \nWHERE\nSupportGroup  LIKE \n  CASE\n    WHEN $__user = 18 THEN 'DXC%'\n    ELSE 'D%' END"
   },
   { "name": "DatabasePattern" },
   {
    "name": "DatabaseName",
    "query": "SELECT name FROM sys.databases WHERE name LIKE '%$DatabasePattern%'"
   }
  ]
 },
 "panels": [
  {
   "title": "$Datasource Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Connections",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT CheckDateTime AS time\r\n  ,SUM(Connections) AS Connections\r\nFROM Archive.DatabaseConnections\r\nWHERE $__timeFilter(CheckDateTime)\r\nAND DatabaseName IN ($DatabaseName)\r\nGROUP BY CheckDateTime\r\nORDER BY time\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource By Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections By Database",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT CheckDateTime AS time\r\n  ,DatabaseName\r\n  ,SUM(Connections) AS Connections\r\nFROM Archive.DatabaseConnections\r\nWHERE $__timeFilter(CheckDateTime)\r\nAND DatabaseName IN ($DatabaseName)\r\nGROUP BY CheckDateTime, DatabaseName\r\nORDER BY time, DatabaseName\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource By IP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections By IP",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT CheckDateTime AS time\r\n  ,ClientNetAddress\r\n  ,SUM(Connections) AS Connections\r\nFROM Archive.DatabaseConnections\r\nWHERE $__timeFilter(CheckDateTime)\r\nAND DatabaseName IN ($DatabaseName)\r\nGROUP BY CheckDateTime, ClientNetAddress\r\nORDER BY time, ClientNetAddress\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource By HostName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections By HostName",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT CheckDateTime AS time\r\n  ,HostName\r\n  ,SUM(Connections) AS Connections\r\nFROM Archive.DatabaseConnections\r\nWHERE $__timeFilter(CheckDateTime)\r\nAND DatabaseName IN ($DatabaseName)\r\nGROUP BY CheckDateTime, HostName\r\nORDER BY time, HostName\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource By LoginName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections By LoginName",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT CheckDateTime AS time\r\n  ,LoginName\r\n  ,SUM(Connections) AS Connections\r\nFROM Archive.DatabaseConnections\r\nWHERE $__timeFilter(CheckDateTime)\r\nAND DatabaseName IN ($DatabaseName)\r\nGROUP BY CheckDateTime, LoginName\r\nORDER BY time, LoginName\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "$Datasource By ProgramName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "Datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections By ProgramName",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT CheckDateTime AS time\r\n  ,ProgramName\r\n  ,SUM(Connections) AS Connections\r\nFROM Archive.DatabaseConnections\r\nWHERE $__timeFilter(CheckDateTime)\r\nAND DatabaseName IN ($DatabaseName)\r\nGROUP BY CheckDateTime, ProgramName\r\nORDER BY time, ProgramName\r\n"
      }
     ]
    }
   ]
  }
 ]
}