{
 "title": "SQLServerOverviewV3",
 "tags": [ "DBA" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "mssql" },
   { "name": "Aggregate", "query": "MIN,MAX,AVG" },
   { "name": "Interval", "query": "MINUTE,HOUR,DAY" },
   { "name": "IntervalValue", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Datasource",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "repeat": "Datasource",
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DATEDIFF(MINUTE,sqlserver_start_time,GETUTCDATE()) FROM sys.dm_os_sys_info; "
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Datasource $Aggregate for $IntervalValue $Interval CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "repeat": "Datasource",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time \r\n  ,$Aggregate(SQLProcessUtilization+OtherProcessUtilization) AS [CPU%]\r\nFROM Archive.ProcessUtilization\r\nWHERE $__timeFilter(CheckDateTime)\r\nGROUP BY DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue\r\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT $__time(T.DataAdd)\r\n  ,$Aggregate(SQLProcessUtilization+OtherProcessUtilization) AS [CPU%_PreviousMonth]\r\nFROM Archive.ProcessUtilization\r\nCROSS APPLY (SELECT DATEADD(MONTH,1,DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')) AS DataAdd) T\r\nWHERE $__timeFilter(T.DataAdd)\r\nGROUP BY T.DataAdd\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "$Datasource $Aggregate for $IntervalValue $Interval Schedulers",
   "type": "timeseries",
   "description": "Task > 10 = Blocking/Deadlocking  \nRunnable > 1 = CPU Pressure  \nPendingDiskIO > 1 = Disk Pressure  ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "repeat": "Datasource",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time \r\n\t,$Aggregate([AverageTaskCount]) AS AverageTaskCount\r\n\t,$Aggregate([AverageRunnableTaskCount]) AS AverageRunnableTaskCount\r\n\t,$Aggregate([AveragePendingDiskIOCount]) AS AveragePendingDiskIOCount\r\nFROM Archive.Schedulers\r\nWHERE $__timeFilter(CheckDateTime)\r\nGROUP BY DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue\r\nORDER BY time ASC\r\n"
    }
   ]
  },
  {
   "title": "$Datasource $Aggregate for $IntervalValue $Interval Schedulers",
   "type": "timeseries",
   "description": "Task > 10 = Blocking/Deadlocking  \nRunnable > 1 = CPU Pressure  \nPendingDiskIO > 1 = Disk Pressure  ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time \r\n\t,$Aggregate([AverageTaskCount]) AS AverageTaskCount\r\nFROM Archive.Schedulers\r\nWHERE $__timeFilter(CheckDateTime)\r\nGROUP BY DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue\r\nORDER BY time ASC\r\n"
    },
    {
     "rawSql": "SELECT $__time(T.DataAdd)\r\n\t,$Aggregate([AverageTaskCount]) AS AverageTaskCount_PreviousMonth\r\nFROM Archive.Schedulers\r\nCROSS APPLY (SELECT DATEADD(MONTH,1,DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')) AS DataAdd) T\r\nWHERE $__timeFilter(T.DataAdd)\r\nGROUP BY T.DataAdd\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Memory Usage (KB)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\nCounterName,\r\n$Aggregate(CounterValue) AS Value\r\nFROM [Archive].PerformanceCounter\r\nWHERE 1=1\r\nAND $__timeFilter(CheckDateTime)\r\nAND CounterName IN ('Total Server Memory (KB)','Lock Memory (KB)','Connection Memory (KB)','Database Cache Memory (KB)')\r\nGROUP BY DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue, CounterName\r\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Lazy writes/sec",
     "type": "timeseries",
     "description": "Should be less than 2",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH LazyWrites AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n    CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Lazy writes/sec')\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   CounterName,\r\n\t   $Aggregate(CounterValue) AS CounterValue\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t     a.CounterName,\r\n       (a.CounterValue - aPrior.CounterValue)/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS CounterValue\r\nFROM LazyWrites a\r\nINNER JOIN LazyWrites aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]\r\n)A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), CounterName\r\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Memory Grants Pending",
     "type": "timeseries",
     "description": "Should be 0",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT  DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n        CounterName,\r\n\t\t$Aggregate(CounterValue) AS Value\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Memory Grants Pending')\r\n\tGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), CounterName\r\n\tORDER BY time ASC"
      }
     ]
    },
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Free list stalls/sec",
     "type": "timeseries",
     "description": "Should be less than 20",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH FreeListStalls AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n    CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Free list stalls/sec')\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   CounterName,\r\n\t   $Aggregate(CounterValue) AS CounterValue\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t     a.CounterName,\r\n       (a.CounterValue - aPrior.CounterValue)/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS CounterValue\r\nFROM FreeListStalls a\r\nINNER JOIN FreeListStalls aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]\r\n)A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), CounterName\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Page Life Expectancy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Page Life Expectancy",
     "type": "timeseries",
     "description": "Calculated PLE per 4GB, threshold fixed at 300 seconds",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\n$Aggregate(PageLifeExpectancyDynamic) AS Value\nFROM Archive.V_PageLifeExpectancy\nWHERE $__timeFilter(CheckDateTime)\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')\nORDER BY time ASC\n"
      },
      {
       "rawSql": "SELECT $__time(T.DataAdd),\n$Aggregate(PageLifeExpectancyDynamic) AS PreviousMonth\nFROM Archive.V_PageLifeExpectancy\nCROSS APPLY (SELECT DATEADD(MONTH,1,DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')) AS DataAdd) T\nWHERE $__timeFilter(T.DataAdd)\nGROUP BY T.DataAdd\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Drive Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": ";WITH DriveIOLatency AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\t    CheckDateTime,\r\n        LEFT(UPPER(PhysicalName), 1) AS Drive,\r\n        SUM(io_stall_read_ms) AS io_stall_read_ms,\r\n        SUM(io_stall_write_ms) AS io_stall_write_ms,\r\n        SUM(num_of_reads) AS num_of_reads,\r\n\t\tSUM(num_of_writes) AS num_of_writes\r\n    FROM [Archive].[FileStatistics]\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n    AND LEFT(UPPER(PhysicalName), 1) = 'G'\r\n    GROUP BY CheckDateTime, LEFT(UPPER(PhysicalName), 1)\r\n)\r\n\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   Drive,\r\n\t   $Aggregate(ReadLatency) AS ReadLatency,\r\n\t   $Aggregate(WriteLatency) AS WriteLatency\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t     a.Drive,\r\n       CASE WHEN(a.num_of_reads-aPrior.num_of_reads) <= 0 THEN 0\r\n       ELSE(a.io_stall_read_ms-aPrior.io_stall_read_ms)*1.0/(a.num_of_reads-aPrior.num_of_reads)*1.0 END AS ReadLatency,\r\n       CASE WHEN(a.num_of_writes-aPrior.num_of_writes) <= 0 THEN 0\r\n       ELSE(a.io_stall_write_ms-aPrior.io_stall_write_ms)*1.0/(a.num_of_writes-aPrior.num_of_writes)*1.0 END AS WriteLatency\r\nFROM DriveIOLatency a\r\nINNER JOIN DriveIOLatency aPrior\r\nON a.Drive = aPrior.Drive\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.num_of_reads >= aPrior.num_of_reads\r\nAND a.num_of_writes >= aPrior.num_of_writes\r\nAND (a.num_of_reads-aPrior.num_of_reads) >= 0\r\nAND (a.io_stall_read_ms-aPrior.io_stall_read_ms) >= 0\r\n) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), Drive\r\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Drive Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": ";WITH DriveIOLatency AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\t    CheckDateTime,\r\n        LEFT(UPPER(PhysicalName), 1) AS Drive,\r\n        SUM(io_stall_read_ms) AS io_stall_read_ms,\r\n        SUM(io_stall_write_ms) AS io_stall_write_ms,\r\n        SUM(num_of_reads) AS num_of_reads,\r\n\t\tSUM(num_of_writes) AS num_of_writes\r\n    FROM [Archive].[FileStatistics]\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n    AND LEFT(UPPER(PhysicalName), 1) = 'G'\r\n    GROUP BY CheckDateTime, LEFT(UPPER(PhysicalName), 1)\r\n)\r\n\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   Drive,\r\n\t   $Aggregate(ReadLatency) AS ReadLatency,\r\n\t   $Aggregate(WriteLatency) AS WriteLatency\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t     a.Drive,\r\n       CASE WHEN(a.num_of_reads-aPrior.num_of_reads) <= 0 THEN 0\r\n       ELSE(a.io_stall_read_ms-aPrior.io_stall_read_ms)*1.0/(a.num_of_reads-aPrior.num_of_reads)*1.0 END AS ReadLatency,\r\n       CASE WHEN(a.num_of_writes-aPrior.num_of_writes) <= 0 THEN 0\r\n       ELSE(a.io_stall_write_ms-aPrior.io_stall_write_ms)*1.0/(a.num_of_writes-aPrior.num_of_writes)*1.0 END AS WriteLatency\r\nFROM DriveIOLatency a\r\nINNER JOIN DriveIOLatency aPrior\r\nON a.Drive = aPrior.Drive\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.num_of_reads >= aPrior.num_of_reads\r\nAND a.num_of_writes >= aPrior.num_of_writes\r\nAND (a.num_of_reads-aPrior.num_of_reads) >= 0\r\nAND (a.io_stall_read_ms-aPrior.io_stall_read_ms) >= 0\r\n) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), Drive\r\nORDER BY time ASC"
      },
      {
       "rawSql": ";WITH DriveIOLatency AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\t    CheckDateTime,\r\n        LEFT(UPPER(PhysicalName), 1) AS Drive,\r\n        SUM(io_stall_read_ms) AS io_stall_read_ms,\r\n        SUM(io_stall_write_ms) AS io_stall_write_ms,\r\n        SUM(num_of_reads) AS num_of_reads,\r\n\t\tSUM(num_of_writes) AS num_of_writes\r\n    FROM [Archive].[FileStatistics]\r\n    CROSS APPLY (SELECT DATEADD(MONTH,1,DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')) AS DataAdd) T\r\n    WHERE 1=1\r\n    AND $__timeFilter(T.DataAdd)\r\n    AND LEFT(UPPER(PhysicalName), 1) = 'G'\r\n    GROUP BY CheckDateTime, LEFT(UPPER(PhysicalName), 1)\r\n)\r\n\r\nSELECT $__time(T.DataAdd),\r\n\t   Drive,\r\n\t   $Aggregate(ReadLatency) AS ReadLatency_PreviousMonth,\r\n\t   $Aggregate(WriteLatency) AS WriteLatency_PreviousMonth\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t     a.Drive,\r\n       CASE WHEN(a.num_of_reads-aPrior.num_of_reads) <= 0 THEN 0\r\n       ELSE(a.io_stall_read_ms-aPrior.io_stall_read_ms)*1.0/(a.num_of_reads-aPrior.num_of_reads)*1.0 END AS ReadLatency,\r\n       CASE WHEN(a.num_of_writes-aPrior.num_of_writes) <= 0 THEN 0\r\n       ELSE(a.io_stall_write_ms-aPrior.io_stall_write_ms)*1.0/(a.num_of_writes-aPrior.num_of_writes)*1.0 END AS WriteLatency\r\nFROM DriveIOLatency a\r\nINNER JOIN DriveIOLatency aPrior\r\nON a.Drive = aPrior.Drive\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.num_of_reads >= aPrior.num_of_reads\r\nAND a.num_of_writes >= aPrior.num_of_writes\r\nAND (a.num_of_reads-aPrior.num_of_reads) >= 0\r\nAND (a.io_stall_read_ms-aPrior.io_stall_read_ms) >= 0\r\n) A\r\nCROSS APPLY (SELECT DATEADD(MONTH,1,DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')) AS DataAdd) T\r\nWHERE $__timeFilter(T.DataAdd)\r\nGROUP BY T.DataAdd, Drive\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O IOPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval R/W IOPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH DriveIOIOPS AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\t    CheckDateTime,\r\n        LEFT(UPPER(PhysicalName), 1) AS Drive,\r\n        SUM(num_of_reads) AS num_of_reads,\r\n\t\tSUM(num_of_writes) AS num_of_writes\r\n    FROM [Archive].[FileStatistics]\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n    AND LEFT(UPPER(PhysicalName), 1) = 'G'\r\n    GROUP BY CheckDateTime, LEFT(UPPER(PhysicalName), 1)\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   Drive,\r\n\t   $Aggregate(ReadIOPS) AS ReadIOPS,\r\n\t   $Aggregate(WriteIOPS) AS WriteIOPS\r\nFROM (\r\nSELECT  a.CheckDateTime,\r\n\t      a.Drive,\r\n        (a.num_of_reads - aPrior.num_of_reads)*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS ReadIOPS,\r\n        (a.num_of_writes - aPrior.num_of_writes)*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS WriteIOPS\r\nFROM DriveIOIOPS a\r\nINNER JOIN DriveIOIOPS aPrior\r\nON a.Drive = aPrior.Drive\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.num_of_reads >= aPrior.num_of_reads\r\nAND a.num_of_writes >= aPrior.num_of_writes) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), Drive\r\nORDER BY time ASC"
      },
      {
       "rawSql": ";WITH DriveIOIOPS AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\t    CheckDateTime,\r\n        LEFT(UPPER(PhysicalName), 1) AS Drive,\r\n        SUM(num_of_reads) AS num_of_reads,\r\n\t\tSUM(num_of_writes) AS num_of_writes\r\n    FROM [Archive].[FileStatistics]\r\n    CROSS APPLY (SELECT DATEADD(MONTH,1,DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')) AS DataAdd) T\r\n    WHERE 1=1\r\n    AND $__timeFilter(T.DataAdd)\r\n    AND LEFT(UPPER(PhysicalName), 1) = 'G'\r\n    GROUP BY CheckDateTime, LEFT(UPPER(PhysicalName), 1)\r\n)\r\nSELECT $__time(T.DataAdd),\r\n\t   Drive,\r\n\t   $Aggregate(ReadIOPS) AS ReadIOPS_PreviousMonth,\r\n\t   $Aggregate(WriteIOPS) AS WriteIOPS_PreviousMonth\r\nFROM (\r\nSELECT  a.CheckDateTime,\r\n\t      a.Drive,\r\n        (a.num_of_reads - aPrior.num_of_reads)*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS ReadIOPS,\r\n        (a.num_of_writes - aPrior.num_of_writes)*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS WriteIOPS\r\nFROM DriveIOIOPS a\r\nINNER JOIN DriveIOIOPS aPrior\r\nON a.Drive = aPrior.Drive\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.num_of_reads >= aPrior.num_of_reads\r\nAND a.num_of_writes >= aPrior.num_of_writes) A\r\nCROSS APPLY (SELECT DATEADD(MONTH,1,DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')) AS DataAdd) T\r\nGROUP BY T.DataAdd, Drive\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval R/W Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "rawSql": ";WITH DriveIOThroughput AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\t    CheckDateTime,\r\n        LEFT(UPPER(PhysicalName), 1) AS Drive,\r\n        SUM(num_of_bytes_read) AS num_of_bytes_read,\r\n\t\tSUM(num_of_bytes_written) AS num_of_bytes_written\r\n    FROM [Archive].[FileStatistics]\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n    AND LEFT(UPPER(PhysicalName), 1) = 'G'\r\n    GROUP BY CheckDateTime, LEFT(UPPER(PhysicalName), 1)\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   Drive,\r\n\t   $Aggregate(ReadThroughputMBPS) AS ReadThroughputMBPS,\r\n\t   $Aggregate(WriteThroughputMBPS) AS WriteThroughputMBPS\r\nFROM (\r\nSELECT  a.CheckDateTime,\r\n\t      a.Drive,\r\n        (a.num_of_bytes_read - aPrior.num_of_bytes_read)/1024/1024*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS ReadThroughputMBPS,\r\n        (a.num_of_bytes_written - aPrior.num_of_bytes_written)/1024/1024*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS WriteThroughputMBPS\r\nFROM DriveIOThroughput a\r\nINNER JOIN DriveIOThroughput aPrior\r\nON a.Drive = aPrior.Drive\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.num_of_bytes_read >= aPrior.num_of_bytes_read\r\nAND a.num_of_bytes_written >= aPrior.num_of_bytes_written) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), Drive\r\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval R/W Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "rawSql": ";WITH DriveIOThroughput AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\t    CheckDateTime,\r\n        LEFT(UPPER(PhysicalName), 1) AS Drive,\r\n        SUM(num_of_bytes_read) AS num_of_bytes_read,\r\n\t\tSUM(num_of_bytes_written) AS num_of_bytes_written\r\n    FROM [Archive].[FileStatistics]\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n    AND LEFT(UPPER(PhysicalName), 1) = 'G'\r\n    GROUP BY CheckDateTime, LEFT(UPPER(PhysicalName), 1)\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   Drive,\r\n\t   $Aggregate(ReadThroughputMBPS) AS ReadThroughputMBPS,\r\n\t   $Aggregate(WriteThroughputMBPS) AS WriteThroughputMBPS\r\nFROM (\r\nSELECT  a.CheckDateTime,\r\n\t      a.Drive,\r\n        (a.num_of_bytes_read - aPrior.num_of_bytes_read)/1024/1024*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS ReadThroughputMBPS,\r\n        (a.num_of_bytes_written - aPrior.num_of_bytes_written)/1024/1024*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS WriteThroughputMBPS\r\nFROM DriveIOThroughput a\r\nINNER JOIN DriveIOThroughput aPrior\r\nON a.Drive = aPrior.Drive\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.num_of_bytes_read >= aPrior.num_of_bytes_read\r\nAND a.num_of_bytes_written >= aPrior.num_of_bytes_written) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), Drive\r\nORDER BY time ASC"
      },
      {
       "rawSql": ";WITH DriveIOThroughput AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\t    CheckDateTime,\r\n        LEFT(UPPER(PhysicalName), 1) AS Drive,\r\n        SUM(num_of_bytes_read) AS num_of_bytes_read,\r\n\t\tSUM(num_of_bytes_written) AS num_of_bytes_written\r\n    FROM [Archive].[FileStatistics]\r\n    CROSS APPLY (SELECT DATEADD(MONTH,1,DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')) AS DataAdd) T\r\n    WHERE 1=1\r\n    AND $__timeFilter(T.DataAdd)\r\n    AND LEFT(UPPER(PhysicalName), 1) = 'G'\r\n    GROUP BY CheckDateTime, LEFT(UPPER(PhysicalName), 1)\r\n)\r\nSELECT $__time(T.DataAdd),\r\n\t   Drive,\r\n\t   $Aggregate(ReadThroughputMBPS) AS ReadThroughputMBPS_PreviousMonth,\r\n\t   $Aggregate(WriteThroughputMBPS) AS WriteThroughputMBPS_PreviousMonth\r\nFROM (\r\nSELECT  a.CheckDateTime,\r\n\t      a.Drive,\r\n        (a.num_of_bytes_read - aPrior.num_of_bytes_read)/1024/1024*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS ReadThroughputMBPS,\r\n        (a.num_of_bytes_written - aPrior.num_of_bytes_written)/1024/1024*1.0/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS WriteThroughputMBPS\r\nFROM DriveIOThroughput a\r\nINNER JOIN DriveIOThroughput aPrior\r\nON a.Drive = aPrior.Drive\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.num_of_bytes_read >= aPrior.num_of_bytes_read\r\nAND a.num_of_bytes_written >= aPrior.num_of_bytes_written) A\r\nCROSS APPLY (SELECT DATEADD(MONTH,1,DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')) AS DataAdd) T\r\nGROUP BY T.DataAdd, Drive\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Maintenance - Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource CommandLog (BACKUP_DATABASE)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',StartTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   DatabaseName,\r\n\t   $Aggregate(Value) AS Value\r\nFROM (\r\nSELECT [StartTime],\r\nDatabaseName,\r\nDATEDIFF(SECOND,StartTime,EndTime) Value\r\n  FROM msdb.[dbo].[CommandLog]\r\n  WHERE 1=1\r\nAND CommandType IN ('BACKUP_DATABASE')\r\nAND $__timeFilter(StartTime))A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',StartTime)/$IntervalValue*$IntervalValue,'2000-01-01'), DatabaseName\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Maintenance - Integrity Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource CommandLog (DBCC_CHECKDB)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',StartTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   DatabaseName,\r\n\t   $Aggregate(Value) AS Value\r\nFROM (\r\nSELECT [StartTime],\r\nDatabaseName,\r\nDATEDIFF(SECOND,StartTime,EndTime) Value\r\n  FROM msdb.[dbo].[CommandLog]\r\n  WHERE 1=1\r\nAND CommandType IN ('DBCC_CHECKDB')\r\n--AND Command LIKE '%DIFF%'\r\nAND $__timeFilter(StartTime)) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',StartTime)/$IntervalValue*$IntervalValue,'2000-01-01'), DatabaseName\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Maintenance - Update Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource CommandLog (UPDATE_STATISTICS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',StartTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   DatabaseName,\r\n\t   $Aggregate(Value) AS Value\r\nFROM (\r\nSELECT StartTime,\r\nDatabaseName,\r\nDATEDIFF(SECOND,(StartTime),(EndTime)) Value\r\n  FROM msdb.[dbo].[CommandLog]\r\n  WHERE 1=1\r\nAND CommandType IN ('UPDATE_STATISTICS')\r\n--AND Command LIKE '%DIFF%'\r\nAND $__timeFilter(StartTime))A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',StartTime)/$IntervalValue*$IntervalValue,'2000-01-01'),DatabaseName\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Maintenance - Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource CommandLog (ALTER_INDEX)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',StartTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   DatabaseName,\r\n\t   $Aggregate(Value) AS Value\r\nFROM (\r\nSELECT StartTime,\r\nDatabaseName,\r\nDATEDIFF(SECOND,StartTime,EndTime) Value\r\n  FROM msdb.[dbo].[CommandLog]\r\n  WHERE 1=1\r\nAND CommandType IN ('ALTER_INDEX')\r\n--AND Command LIKE '%DIFF%'\r\nAND $__timeFilter(StartTime))A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',StartTime)/$IntervalValue*$IntervalValue,'2000-01-01'),DatabaseName\r\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Maintenance Jobs",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "\t   SELECT sJOB.name AS JobName\r\n\t\t, msdb.dbo.agent_datetime(run_date, run_time) AS RunStartTime\r\n\t\t, ( run_duration / 10000 * 60 * 60 ) + ( run_duration / 100 % 100 * 60 ) + ( run_duration % 100 ) AS RunDuration --seconds\r\n\t\t\t, sJOBH.run_status AS RunStatus\r\n\t\t\t--, CASE WHEN sJOBH.run_status = 0 THEN 'Failed'\r\n\t\t\t--\t   WHEN sJOBH.run_status = 1 THEN 'Succeeded'\r\n\t\t\t--\t   WHEN sJOBH.run_status = 2 THEN 'Retry'\r\n\t\t\t--\t   WHEN sJOBH.run_status = 3 THEN 'Canceled'\r\n\t\t\t--\t   WHEN sJOBH.run_status = 4 THEN 'In Progress'\r\n\t\t\t--END AS RunStatus\r\n\t   FROM msdb.dbo.sysjobs AS sJOB\r\n\t   LEFT JOIN\r\n\t   (\r\n\t\t   SELECT job_id\r\n\t\t\t\t, step_name\r\n\t\t\t\t, run_date\r\n\t\t\t\t, run_time\r\n\t\t\t\t, run_status\r\n\t\t\t\t, run_duration\r\n\t\t\t\t, message\r\n\t\t\t\t, ROW_NUMBER() OVER(PARTITION BY job_id\r\n\t\t\t\t\t\t\t\t\t\t\t   , step_id\r\n\t\t\t\t  ORDER BY run_date DESC\r\n\t\t\t\t\t\t , run_time DESC) AS RowNumber\r\n\t\t   FROM msdb.dbo.sysjobhistory\r\n\t\t   WHERE step_id <> 0\r\n\t   ) AS sJOBH ON sJOB.job_id = sJOBH.job_id AND \r\n\t\t\t\t\t sJOBH.RowNumber = 1\r\n\t\r\n\t   WHERE sJOB.enabled = 1 AND \r\n\t   ( sJOB.name LIKE 'DBA_SystemDatabaseBackup%'\r\n\t   OR sJOB.name LIKE 'DBA_UserDatabaseBackup%'\r\n\t   OR sJOB.name LIKE 'DBA_UpdateStatistics'\r\n\t   OR sJOB.Name LIKE 'DBA_SystemDatabaseIntegrityCheck'\r\n\t   OR sJOB.Name LIKE 'DBA_UserDatabaseIntegrityCheck'\r\n\t   OR sJOB.Name LIKE 'DBA_IndexMaintenance'\r\n\t   )\r\n\t\t\t OPTION(RECOMPILE);"
      }
     ]
    }
   ]
  },
  {
   "title": "Wait Statistics - Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Waits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": ";WITH WaitStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        WaitType,\r\n\t\tWaitCount,\r\n\t\tWait_Seconds\r\n    FROM [Archive].WaitStatistics\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   WaitType,\r\n\t   $Aggregate(Value) AS Value\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t   a.WaitType,\r\n\t   --(a.WaitCount - aPrior.WaitCount) AS WaitCountDelta,\r\n       (a.[Wait_Seconds] - aPrior.[Wait_Seconds]) AS Value\r\nFROM WaitStatistics a\r\nINNER JOIN WaitStatistics aPrior\r\nON a.WaitType = aPrior.WaitType\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.WaitCount >= aPrior.WaitCount) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), WaitType\r\nORDER BY time ASC\r\n\r\n\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Wait Statistics - AVG",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Avg Waits",
     "type": "timeseries",
     "description": "Waits/WaitCount",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": ";WITH WaitStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n    WaitType,\r\n\t\tWaitCount,\r\n\t\tWait_Seconds\r\n    FROM [Archive].WaitStatistics\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   WaitType,\r\n\t   $Aggregate(Value) AS Value\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t   a.WaitType,\r\n    (a.[Wait_Seconds] - aPrior.[Wait_Seconds]) / NULLIF((a.[WaitCount] - aPrior.[WaitCount]),0) AS Value\r\nFROM WaitStatistics a\r\nINNER JOIN WaitStatistics aPrior\r\nON a.WaitType = aPrior.WaitType\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.WaitCount >= aPrior.WaitCount) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), WaitType\r\nORDER BY time ASC\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Wait Statistics - Signals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Signal Waits",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": ";WITH WaitStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n    WaitType,\r\n\t\tWaitCount,\r\n\t\tWait_Seconds,\r\n\t\tSignal_Seconds\r\n    FROM [Archive].WaitStatistics\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   $Aggregate([%signal (cpu) waits]) AS [%signal (cpu) waits],\r\n\t   $Aggregate([%resource waits]) AS [%resource waits]\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t   CAST(100.0 * SUM(a.Signal_Seconds-aPrior.Signal_Seconds) / NULLIF(SUM(a.Wait_Seconds-aPrior.Wait_Seconds),0) AS NUMERIC(20, 2)) AS [%signal (cpu) waits],\r\n     CAST(100.0 * SUM((a.Wait_Seconds-aPrior.Wait_Seconds) - (a.Signal_Seconds-aPrior.Signal_Seconds)) / NULLIF(SUM(a.Wait_Seconds-aPrior.Wait_Seconds),0) AS NUMERIC(20, 2)) AS [%resource waits]\r\nFROM WaitStatistics a\r\nINNER JOIN WaitStatistics aPrior\r\nON a.WaitType = aPrior.WaitType\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.WaitCount >= aPrior.WaitCount\r\nGROUP BY a.CheckDateTime) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Wait Statistics - Signals by Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Signal Waits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": ";WITH WaitStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n    WaitType,\r\n\t\tWaitCount,\r\n\t\tWait_Seconds,\r\n\t\tSignal_Seconds\r\n    FROM [Archive].WaitStatistics\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   WaitType,\r\n\t   $Aggregate([%signal (cpu) waits]) AS [%signal (cpu) waits],\r\n\t   $Aggregate([%resource waits]) AS [%resource waits]\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t   a.WaitType,\r\n\t   CAST(100.0 * SUM(a.Signal_Seconds-aPrior.Signal_Seconds) / NULLIF(SUM(a.Wait_Seconds-aPrior.Wait_Seconds),0) AS NUMERIC(20, 2)) AS [%signal (cpu) waits],\r\n     CAST(100.0 * SUM((a.Wait_Seconds-aPrior.Wait_Seconds) - (a.Signal_Seconds-aPrior.Signal_Seconds)) / NULLIF(SUM(a.Wait_Seconds-aPrior.Wait_Seconds),0) AS NUMERIC(20, 2)) AS [%resource waits]\r\nFROM WaitStatistics a\r\nINNER JOIN WaitStatistics aPrior\r\nON a.WaitType = aPrior.WaitType\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.WaitCount >= aPrior.WaitCount\r\nGROUP BY a.CheckDateTime,a.WaitType) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), WaitType\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Activity - SQL Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval SQL Statistics",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Batch Requests/sec',\r\n                         'SQL Compilations/sec',\r\n                         'SQL Re-Compilations/sec')\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   CounterName,\r\n\t   $Aggregate(CounterValue) AS CounterValue\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue])\r\n\t   /\r\n\t   CASE WHEN DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) = 0 THEN 1 ELSE DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) END AS CounterValue\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), CounterName\r\nORDER BY time ASC\r\n"
      }
     ]
    },
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval SQL Statistics Compare",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Batch Requests/sec')\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   CounterName,\r\n\t   $Aggregate(CounterValue) AS CounterValue\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue])\r\n\t   /\r\n\t   CASE WHEN DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) = 0 THEN 1 ELSE DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) END AS CounterValue\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), CounterName\r\nORDER BY time ASC\r\n"
      },
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n\tCROSS APPLY (SELECT DATEADD(MONTH,1,DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')) AS DataAdd) T\r\n    WHERE 1=1\r\n    AND $__timeFilter(T.DataAdd)\r\n\tAND CounterName IN ('Batch Requests/sec')\r\n)\r\nSELECT $__time(T.DataAdd),\r\n\t   CounterName+'_PreviousMonth',\r\n\t   $Aggregate(CounterValue) AS CounterValue\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue])\r\n\t   /\r\n\t   CASE WHEN DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) = 0 THEN 1 ELSE DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) END AS CounterValue\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]) A\r\nCROSS APPLY (SELECT DATEADD(MONTH,1,DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01')) AS DataAdd) T\r\nWHERE $__timeFilter(T.DataAdd)\r\nGROUP BY T.DataAdd, CounterName\r\nORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Activity - Page Splits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Page Splits/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Page Splits/sec')\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   CounterName,\r\n\t   $Aggregate(CounterValue) AS CounterValue\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue])/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS CounterValue\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue]) A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), CounterName\r\nORDER BY time ASC\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Activity - Forwarded Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Forwarded Records/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n\t\tCheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Forwarded Records/sec')\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   CounterName,\r\n\t   $Aggregate(CounterValue) AS CounterValue\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue])/DATEDIFF(ss, aPrior.CheckDateTime, a.CheckDateTime) AS CounterValue\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue])A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), CounterName\r\nORDER BY time ASC\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity - Free %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource Free Space Less Than 20%",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\n\t   DriveLetter,\n\t   $Aggregate([Free%]) AS [Free%]\nFROM (\nSELECT CheckDateTime, \n       DriveLetter,\n       (TotalSizeMB - (TotalSizeMB - FreeSizeMB))*1.0/TotalSizeMB * 100.0 AS [Free%]\nFROM Archive.DriveSize\nWHERE 1=1\nAND $__timeFilter(CheckDateTime)\nAND (TotalSizeMB - (TotalSizeMB - FreeSizeMB))*1.0/TotalSizeMB * 100.0 < 20) A\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), DriveLetter\nORDER BY time ASC\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity - Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Used Space",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\n\t   DriveLetter,\n\t   $Aggregate(UsedSizeMB) AS UsedSize\nFROM (\nSELECT CheckDateTime, \n       DriveLetter,\n       TotalSizeMB - FreeSizeMB AS UsedSizeMB\nFROM Archive.DriveSize\nWHERE 1=1\nAND $__timeFilter(CheckDateTime))A\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), DriveLetter\nORDER BY time ASC\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity - By Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource Database Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval, DATEDIFF($Interval, 0, CheckDateTime),0) AS time, \r\n  CASE WHEN LEFT(DatabaseName,3) = 'KPD' THEN 'KPDB%'\r\n       WHEN LEFT(DatabaseName,3) = 'SCG' THEN 'SCG%'\r\n       WHEN LEFT(DatabaseName,3) = 'Par' THEN 'Partner%'\r\n  ELSE MAX(DatabaseName)\r\n  END AS DatabaseType, \r\n  SUM([UsedSizePage]* 8) AS Value\r\nFROM [Archive].[DatabaseSize]\r\n  WHERE $__timeFilter(CheckDateTime)\r\n  AND DatabaseName NOT IN ('AdminSQL','DBManagement','master','msdb','model','tempdb')\r\n  GROUP BY DATEADD($Interval, DATEDIFF($Interval, 0, CheckDateTime),0), LEFT(DatabaseName,3)\r\n  ORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocking - Extended Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $IntervalValue $Interval Processes Blocked (Extended Events)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',EventTimeStamp)/$IntervalValue*$IntervalValue,'2000-01-01') AS time, \n       SUM(DurationMS/1000) AS Duration,\n       SUM(TotalBlockCount) AS TotalBlockCount\nFROM Archive.BlockedProcessReport\nWHERE 1=1\nAND $__timeFilter(CheckDateTime)\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',EventTimeStamp)/$IntervalValue*$IntervalValue,'2000-01-01')\nORDER BY time ASC\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocking - Performance Counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Processes blocked (performance counter)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   CounterName,\r\n\t   $Aggregate([Value]) AS [Value]\r\nFROM (\r\nSELECT  CheckDateTime,\r\n        CounterName,\r\n\t\tCounterValue AS Value\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\tAND CounterName IN ('Processes blocked'))A\r\n\tGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), CounterName\r\n\tORDER BY time ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocking - Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource Processes Blocked Details",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT EventTimeStamp,\n       TotalBlockCount,\n       BlockedProcess,\n       BlockingProcess,\n       BlockedClientApp,\n       BlockedHostName,\n       BlockedLoginName,\n       BlockedIsolationLevel,\n       BlockingClientApp,\n       BlockingHostName,\n       BlockingLoginName,\n       BlockingIsolationLevel\nFROM Archive.BlockedProcessReport\nWHERE 1=1\nAND $__timeFilter(CheckDateTime)\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Deadlock - Performance Counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Locks Performance Counter",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": ";WITH SQLStatistics AS\r\n(\r\n    SELECT DENSE_RANK() OVER (\r\n            ORDER BY CheckDateTime ASC\r\n            ) AS ID,\r\n    CheckDateTime,\r\n    CounterName AS CounterName,\r\n\t\tCounterValue AS CounterValue\r\n    FROM [Archive].PerformanceCounter\r\n    WHERE 1=1\r\n    AND $__timeFilter(CheckDateTime)\r\n\t  AND CounterName IN ('Number of Deadlocks/sec',\r\n\t\t\t\t\t\t\t'Lock Timeouts (timeout > 0)/sec')\r\n)\r\nSELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01') AS time,\r\n\t   CounterName,\r\n\t   $Aggregate([Value]) AS [Value]\r\nFROM (\r\nSELECT a.CheckDateTime,\r\n\t     a.CounterName,\r\n       (a.[CounterValue] - aPrior.[CounterValue]) AS Value\r\nFROM SQLStatistics a\r\nINNER JOIN SQLStatistics aPrior\r\nON a.CounterName = aPrior.CounterName\r\nAND a.ID - 1 = aPrior.ID\r\nWHERE a.[CounterValue] >= aPrior.[CounterValue])A\r\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',CheckDateTime)/$IntervalValue*$IntervalValue,'2000-01-01'), CounterName\r\nORDER BY time ASC\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Deadlock - Extended Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Deadlocks (Extended Events)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',EventTimeStamp)/$IntervalValue*$IntervalValue,'2000-01-01') AS time, \n       COUNT(*) AS DeadlockCount\nFROM Archive.XMLDeadlockReport\nWHERE 1=1\nAND $__timeFilter(EventTimeStamp)\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',EventTimeStamp)/$IntervalValue*$IntervalValue,'2000-01-01')\nORDER BY time ASC\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Deadlock - By Object",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Deadlocks by Object",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',EventTimeStamp)/$IntervalValue*$IntervalValue,'2000-01-01') AS time, \n       LockedObject,\n       COUNT(*) AS DeadlockCount\nFROM Archive.XMLDeadlockReportShredded\nWHERE 1=1\nAND $__timeFilter(EventTimeStamp)\nAND LockedObject IS NOT NULL\nAND Victim = 1\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',EventTimeStamp)/$IntervalValue*$IntervalValue,'2000-01-01'),LockedObject\nORDER BY time ASC\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource $Aggregate for $IntervalValue $Interval Error Reported",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',EventTimeStamp)/$IntervalValue*$IntervalValue,'2000-01-01') AS time, \n       CAST(ErrorNumber AS VARCHAR(5)) AS Error,\n       CAST(Severity AS VARCHAR(2)) AS Severity,\n       CAST(ErrorMessage AS VARCHAR(50)) AS ErrorMessage,\n       COUNT(*) AS Value\nFROM Archive.ErrorReported E\nWHERE 1=1\nAND $__timeFilter(EventTimeStamp)\nGROUP BY DATEADD($Interval,DATEDIFF($Interval,'2000-01-01',EventTimeStamp)/$IntervalValue*$IntervalValue,'2000-01-01'), CAST(ErrorNumber AS VARCHAR(5)), CAST(Severity AS VARCHAR(2)),CAST(ErrorMessage AS VARCHAR(50))\nORDER BY time ASC\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors - Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$Datasource Error Reported Details",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 42 },
     "repeat": "Datasource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT EventTimeStamp, \n       ErrorNumber,\n       Severity,\n       ErrorMessage,\n       [SQLText],\n       [ClientAppName], \n       [ClientHostName], \n       [DatabaseName], \n       [ServerPrincipalName]\nFROM Archive.ErrorReported E\nWHERE 1=1\nAND $__timeFilter(EventTimeStamp)\n\n"
      }
     ]
    }
   ]
  }
 ]
}